### ISSUE TITLE
Demo Page Not working in IE 11

### ISSUE THREAD

**Issue by humphries40** [Hacker0x01/react-datepicker#1004]
I tried to open https://hacker0x01.github.io/react-datepicker/ in IE 11 and the page is unable to display.

**Comment by rafeememon** [comment]
What is the error you're seeing?

**Comment by humphries40** [comment]
The first is this.

![image](https://user-images.githubusercontent.com/2933741/29843504-220178f0-8cda-11e7-9c59-a7f2c924d5ee.png)

The 2-6 are all the same basically, and most likely are because of the first. 
![image](https://user-images.githubusercontent.com/2933741/29843572-5e309b62-8cda-11e7-8a31-76a244b9a8b3.png)

**Comment by rafeememon** [comment]
Looks like the problem is [here](https://github.com/Hacker0x01/react-datepicker/blob/v0.53.0/docs-site/src/examples/timezone_date.jsx#L36) because [IE doesn't support `Array.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).  PRs to fix the problem are welcome

**Comment by danielvip98** [comment]
Has this been fixed, it seems the problem continues on IE11
