### ISSUE TITLE
(IE11) - Layout problem when clearable datepicker receives focus

### ISSUE THREAD

**Issue by studiojms** [Hacker0x01/react-datepicker#1017]
I am using the version 0.54.0 of react-datepicker and when rendering the component in IE browser (tested with version 11), it show an **X** character behind the close icon, as showed in the attached image:

![image](https://user-images.githubusercontent.com/158855/30127753-aef44e44-9316-11e7-9050-5f2542ec3d09.png)

There are two X characters, one inside the blue circle (representing the clear button) and behind this one, there is an X of the same color as the text of the input (in this image, red).

**Comment by rafeememon** [comment]
You may be able to hide the red X from IE using this method: https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs  I could see a case for adding this to the default styles of the datepicker.

**Comment by jmsstudio** [comment]
I didn't understand why not adding to the default styles. 
I wonder if it wouldn't be possible to add this rule direct for the scenario:
```
.datepickerClass > input::-ms-clear { display: none; }
```
What do you think?

**Comment by rafeememon** [comment]
As I mentioned, this would be a breaking change for people relying on the X.  It's a minor change but we should still carefully consider it.  In the meantime, you can use the styles in your stylesheet.

**Comment by jmsstudio** [comment]
Ok, I'll follow this idea and change it in my project.

About people relying on this X, the idea is to disable the X only for those inputs that are using the datepicker with the clearable option set to true, thus, it shouldn't affect other components of any page. 
I am saying that again because I believe it conflicts with the idea of supporting IE 10+ as stated in the project page. 
Do you think there could be, in a future version, something (configuration, specific optional component css class etc.) that could include such feature in a way the user doesn't need to customize anything, but instead, activate the behavior on the component itself?
