### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#118]
The current examples don't cover all features of the datepicker. We should make sure all features are covered in the examples.

We can use Github pages to create a nice example page. I imagine something that shows the code example on the left and the actual output on the right for each feature/example.

Optionally, we could use React Playgrounds to give people the ability to play with the code within the example page.

**Comment by tom-james-watson** [comment]
Some basic documentation of how to use the date picker could be included in the README as a start

**Comment by martijnrusschen** [comment]
Agreed. I'll take a pass on this soon!

**Comment by MahatmaManic** [comment]
+1. I've installed react-datepicker and am trying to make use of it. Currently I am using:

var DatePicker = require('react-datepicker);

and then in render adding a 
<DatePicker /> 
to my component heirarchy. 

That seems to show up, but when I select it everything goes very bad (a long column of unstyled text). I looked in the examples, but they all specifically refer to src files rather than using datepicker as a module.

I'm sure I'm doing something ridiculous wrong. Can you help me understand what I should do differently?

**Comment by martijnrusschen** [comment]
Ref http://www.gpbl.org/react-day-picker/#examples/Basic calendar

**Comment by martijnrusschen** [comment]
@MahatmaManic Did you try to add the stylesheet by yourself?

**Comment by martijnrusschen** [comment]
New examples are added to https://hacker0x01.github.io/react-datepicker

**Comment by tom-james-watson** [comment]
There's still no code examples, i.e. what props are expected etc.
