### ISSUE TITLE
some months appearing twice

### ISSUE THREAD

**Issue by AgentChris** [Hacker0x01/react-datepicker#1270]
### Expected behavior
When i click to see the next month i should see the next month, if the date picker is above the input
### Actual behavior
When i am on september month and i click to see the next month, it doesn't change the month, just after the second click
### Steps to reprodcue
![screen shot 2018-02-13 at 12 22 18](https://user-images.githubusercontent.com/10263405/36145024-b164bcb6-10b8-11e8-90b7-44019b6f95ad.png)
![screen shot 2018-02-13 at 12 21 50](https://user-images.githubusercontent.com/10263405/36145031-b80da154-10b8-11e8-9c2e-91fb9e678aab.png)

**Comment by sumit-meshmd** [comment]
facing the same issue.

**Comment by aij** [comment]
I think the problem is that the datepicker in popper behaves weird when resizing (#361), so the calendar ends up  moving on mouse down and you end up not finishing the first click.

To confirm, can you test on the `fixedHeight` example?

Another test is to click very deliberately: Press the mouse button down on the arrow, observe whether or not the arrow moves, and make sure the mouse is still over the arrow when you release the button.
