### ISSUE TITLE
Suggestion: support Luxon

### ISSUE THREAD

**Issue by trevordmiller** [Hacker0x01/react-datepicker#1283]
[Luxon](https://github.com/moment/luxon) is the new, leaner version of Moment.js. Have you considered supporting it so moment.js isn't required?

**Comment by Architektor** [comment]
Looking forward to see that too

**Comment by aij** [comment]
This seems like a special-case of #382 .

@prayerslayer has already moved all the moment code to `src/date_utils.js` in #1046 and #1052, so it should now be a fairly simple*** matter of implementing that API on top of Luxon.

I expect PRs would be welcome if anyone cares to support Luxon.

***: No guarantees as to how simple it will actually be.

**Comment by prayerslayer** [comment]
Yeah, there's also a half-baked POC in #1059 to support any date library as backend. However straight-up replacing `moment` is simpler than adding `luxon` support, because we don't need to care about changing the build process and how to distribute `react-datepicker` with exchangeable date backends.

We could replace `moment`, release a new major version, then check if `date-fns` support is still desirable.

**Comment by trevordmiller** [comment]
Ah yeah 382 looks great. Closing this in favor of that!
