### ISSUE TITLE
After setting time or manual input can no longer inject new moment

### ISSUE THREAD

**Issue by tomtwttr** [Hacker0x01/react-datepicker#1295]
![bug](https://user-images.githubusercontent.com/33262427/36992644-65b98550-2060-11e8-9f07-76dd4e48cca7.gif)

### Expected behavior
Should be able to manually edit time and then inject a new moment.

### Actual behavior
Editing the time manually or through the UI doesn't let you change the input through props.

### Steps to reproduce
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import moment from 'moment';

class App extends Component {

  constructor(props){
    super(props);
    this.state = {
      selected: moment().subtract(1,'months')
    };
    this.format = "LLL";
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <DatePicker
            dateFormat='MMMM DD, YYYY h:mm A'
            selected={this.state.selected}
            allowSameDay
            onChange={this.onChange}
            showTimeSelect
            timeIntervals={15}
            disabledKeyboardNavigation
        />
        <button type="button" onClick={this.onClick}>Change time to now</button>
      </div>
    );
  }

  onClick = () => {
    this.setState({selected: moment()});
  }

  onChange = (date) => {
    console.log(date.format(this.format));
    this.setState({selected: date});
  }
}

export default App;
```

**Comment by aij** [comment]
I think we should be very careful about discarding user input. Discarding user input when the `selected` prop changes is not backwards compatible, because that can happen in the middle of typing in a date.

There was discussion of resetting the state on blur, which doesn't seem quite right but might not be awful. (Eg: User almost finishes typing, but switching apps forces them to start over. Of course, it's not like they should be typing *that* much into the input.)

I see at least two workarounds which would not require incompatible changes:

A) Take control of the input by passing `value` and `onChangeRaw` props. (This gives you a lot more flexibility than you may want to deal with.)

or B) Make your intention to reset user input explicit by passing `ref={p => { this.datepicker = p; }}`, and change onClick to
```
  onClick = () => {
    this.datepicker.clear();
    this.setState({selected: moment()});
  }
```
B seems a bit hacky but might be less code... Note that calling `.clear()` will trigger `onChange(null)`. (Not sure whether that was intentional...)

We probably could/should improve the default state management behavior, but it would probably be backwards incompatible, and there doesn't seem to be consensus on how it should work. Part of the problem stems from using `onChange` for both "the user has selected a new date" and "the current input can be parsed as a date (but there is no indication the user is done typing)".

**Comment by tomtwttr** [comment]
Yes, after thinking about it for quite some time blur is the only thing that seems to work. Hence https://github.com/Hacker0x01/react-datepicker/pull/1303. I think switching apps mid date picker input typing is an unlikely use case, so I bet it's okay to do this change. If we're super worried about it we could add a flag, but I don't think this use case is likely, and I think the bug it produces in this use-case  more likely.
