### ISSUE TITLE
Locale prop not used

### ISSUE THREAD

**Issue by Stalyon** [Hacker0x01/react-datepicker#1316]
### Expected behavior
I would like to use locale prop in my DatePicker, just like in the example:
```
        <DatePicker
          selected={this.state.startDate}
          onChange={this.handleChange}
          locale="fr"
          todayButton={"Aujourd'hui"}
        />
```

But, it seems to not work because it is still in English.
My dependencies are:
```
    "moment": "2.21.0",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-datepicker": "1.2.2"
```

### Steps to reproduce
I created a simple example in this CodeSandBox: https://codesandbox.io/s/5383o29jpx.

**Comment by indapublic** [comment]
Same with `ru` locale. Using as property or moment global - there is no difference

**Comment by indapublic** [comment]
Fixed by importing moment locale
import moment from 'moment'
import 'moment/locale/ru'
moment.locale('ru')

**Comment by martijnrusschen** [comment]
Yep that's the way to do it 👍

**Comment by Rolando-Barbella** [comment]
How can you do this dynamically?  I need something  like  `import` `moment/src/locale/${Locale2}` so I can have rtl style depending on the language, but javascript doesn't allow you to this. 

Doing this  `locale=Locale2` on the component doesn't work either.

**Comment by indapublic** [comment]
@Rolando-Barbella I think you should import all 20 different languages yourself.

**Comment by NastyaArt** [comment]
### It was a big problem for me. Please, add to Docs some words about localization with moment.
For me works next:
1. Import all necessary langs (or just one, if it static):
```
import 'moment/locale/ru';
import 'moment/locale/fr';
import 'moment/locale/en-gb';
...
```
**Note:** be careful, because last imported locale stay as default, if you don't set locale for DatePicker or if you set locale that has not been imported.

2. Add locale prop for DatePicker. It can be value from state or props or other variable, which you use to manage locale (or just string, if it static).
```
this.state = {
     locale: "ru"
};
```
```
<DatePicker
      locale={this.state.locale}
...
 />```
