### ISSUE TITLE
The react-datepicker is slow if I pass an array of 500 dates to excludedDates

### ISSUE THREAD

**Issue by MANOJPATRA1991** [Hacker0x01/react-datepicker#1415]

**Comment by atkingtornado** [comment]
I'm having the same problem... any updates would be appreciated!

**Comment by atkingtornado** [comment]
This is still an issue... any updates?

**Comment by janeschindler** [comment]
I get this too.

**Comment by Ramosok** [comment]
У меня такая же проблема, возможно есть решение?

**Comment by jukkahuuskonen** [comment]
I had this same problem and it seems it got worse with update from v7 to v8 (I also sarted using TZDate at that point, slowing may be due to it. However I did manage to create a solution for the slowness.

I started to filter the excluded dates based on the current visible month in the DatePicker (+7 extra days both start and end to take into account the overflow from next/prev month if needed).
Initially **filter** variable is based on the currently **selected** date and is updated every time the month/year of the **selected** date is changed.
**filter** is updated every time:
1. Calendar **selected** changes if **selected** dates month changes
2. Calendar visible month is changed **onMonthChange**-prop gives a date in currently visible month
3. Calendar is closed **onClickOutside** (or any other way it gets closed) **filter** is set to based on currently **selected** date

I hope this helps others battling with this slowness problem.

I think this solution would a nice fit in Datepicker itself.
