### ISSUE TITLE
BUG: value in input isn't updated when selected prop is reset.

### ISSUE THREAD

**Issue by karlkras** [Hacker0x01/react-datepicker#1502]
### Expected behavior
When the prior initialized picker has the selected property reset on event, the associated input field should be updated accordingly.

### Actual behavior
the selected prop is reset, but input text stays static.

### Steps to reproduce
1) initialize a datepicker with a valid controlled selected prop with onChange and onBlur handlers and an editable "value" text input so when initialized, the formatted date will populate the input, e.g., `12/25/2018`.
2) Manually delete all characters in the input.
3) At this point the selected property should be `null`.
4) In the onBlur handler, check for the selected property to be `null`, and it if is, reinitialize the selected state object.
5) After event, notice the input remains blank, but the date is set to the selected prop value.

**Comment by karlkras** [comment]
Help?

**Comment by gangwar1** [comment]
i am also facing the same issue.

**Comment by NguyenDa18** [comment]
@karlkras , @gangwar1 
The 'selected' prop is only set when you trigger the 'onChange' prop when you choose a date on the datepicker. The prop 'onChangeRaw' is what is actually connected to the input box. When you make a change in the input box, onChangeRaw should do the handling like so:
```javascript
<Datepicker
 onChangeRaw={e => customHandler(moment(e.target.value))}
selected={date => }
/>
```

Hope this helps!

**Comment by karlkras** [comment]
Actually, unfortunately it doesn't.
Consider my [sample code here ](https://github.com/Hacker0x01/react-datepicker/issues/1272#issuecomment-425146868)
I am catching this on the onChange callback, and when it's null, as it will be if you delete the entire input, I set it back to the original date via the selected value being linked to my state. Bug

**Comment by NguyenDa18** [comment]
@karlkras 
I worked out something that might fulfill your case. I had to set a prop to your custom component. I've worked with react-datepicker using redux and that was how we got the default date to show, because it was stored as a prop in the global state. Hope this helps.
[![Edit DatePicker Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4w7ql4lvjw)

**Comment by karlkras** [comment]
oh, using the placeholder. simple but clever. thanks!

**Comment by NguyenDa18** [comment]
@karlkras Thanks for liking my solution! CodeSandbox is fantastic for snippets like these -check out Repl.It as well! Happy coding.

**Comment by jmitchell33** [comment]
I'm currently having the same issue.  That sandbox link no longer works...Any chance you have the code @NguyenDa18 ?  Really having problems because of this and I don't want to change my DatePicker widget at this point.

What really puzzles me is if you completely Unmount / Remount the component, the value of the date is incorrect (I assume the problem is how the form is controlled).  For example, add key to the component in a wrapper or the div, which will cause the component to unmount/remount when that key is changed.  If you start with a specific date in the state (that is being passed via selected props from a Parent Component), proceed to change that date, then unmount / remount the component, the date does not reflect the date in the props, but the date that was selected.

Parent Component:
    this.state = {
        sample_key : uuidv4(),
        sample_date : new Date(1, 1, 1)
    }
    render() {
        return (
            <Child_Component same_date={this.state.sample_date} />
        );
    }

Child Component:
    function updateKey() {
        this.setState({sample_key : uuidv4()})
    }
    render() {
        <div key={this.state.sample_key} onClick={this.updateKey}>
            <DatePicker selected={this.props.sample_date} />
        </div>
    }

**Comment by NguyenDa18** [comment]
Hi @jmitchell33 I apologize for deleting the sandbox when it could have helped others. I tried reconstructing my solution and this time just using local storage to store most recently dates to show in the placeholder when all is blank. Using this component has been a real pain because of the amount of bugs found when you use the onChangeRaw function. I will try doing an example based off of the snippet you gave above but hope this helps for now:
https://codesandbox.io/s/datepicker-example-k2m8p?fontsize=14

**Comment by iloveip** [comment]
Hi @NguyenDa18,

Do you have an example of reseting the datepicker after reseting a redux-form or react-final-form?

**Comment by NguyenDa18** [comment]
@iloveip Still a work in progress but here is an example of redux-form with React Datepicker:
https://codesandbox.io/s/redux-form-simple-example-p2wkr

**Comment by iloveip** [comment]
@NguyenDa18 thank you very much, but there are two problems. First, the value of the input itself is not updated when a date is selected. And the second, the date in the form values is one day behind the date selected in the datepicker due to timezone offset. Do you know how it can be fixed?

**Comment by NguyenDa18** [comment]
Hi @iloveip I haven't been able to work on the example yet but to update the date input you will need a piece of local state for that page and only when a correct date format is used or when the form is submitted should the date propagate to redux-form store. The react-datepicker and moment.js (the date logic behind the component) documentation might be able to help you there.

**Comment by iloveip** [comment]
For anyone who has the same problem, here is a codesandbox of reseting react-datepicker in `react-final-form`. See this [SO question](https://stackoverflow.com/questions/59173990/clear-react-datepicker-on-form-reset-in-react-final-form) for more details.

[![Edit react-datepicker clear](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-datepicker-clear-bu460?fontsize=14)
