### ISSUE TITLE
Can't get keyboard input to disable

### ISSUE THREAD

**Issue by Daniel-Itemize** [Hacker0x01/react-datepicker#1512]
### Expected behavior

Disable keyboard navigation 
I wanted to use that flag to only allow for the clicking of dates. It looks like it is not working. Checkout the behavior on: https://reactdatepicker.com/#example-23

### Actual behavior

You can type your heart out.

### Steps to reproduce
Go to example:
https://reactdatepicker.com/#example-23

or insert ```disabledKeyboardNavigation``` onto the DatePicker component.

**Comment by WesselKroos** [comment]
@Daniel-Itemize disabledKeyboardNavigation does actually do something else than you expect. It disables navigating through the dates squares in the datepicker popup with the arrow keys on your keyboard. By adding disabledKeyboardNavigation you enable the user to use the arrow keys to move the cursor position in the input field rather than moving throught the popup.

**Comment by Daniel-Itemize** [comment]
Thanks for your response. I found a work around. Best!

**Comment by vaibhav-systango** [comment]
@Daniel-Itemize what was the solution around same ?

**Comment by pkudla** [comment]
Who knows?
