### ISSUE TITLE
Refs Error

### ISSUE THREAD

**Issue by johnwp** [Hacker0x01/react-datepicker#157]
On line 678 of dist/react-datepicker.js:
Uncaught TypeError: Cannot read property 'focus' of null

	  toggleFocus: function toggleFocus(focus) {
	    if (focus) {
	      React.findDOMNode(this.refs.input).focus();
	    } else {
	      React.findDOMNode(this.refs.input).blur();
	    }
	  },

**Comment by martijnrusschen** [comment]
Which version of React are you running?

**Comment by jotaen** [comment]
This maybe somewhat unrelated, but I stumbled across the same error when using Datepicker with the `customInput` property: In this case you need to ensure, that you pass a stateful component, and not a functional one. That solves the error in this context, because stateless components cannot be `ref`ed in React.
