### ISSUE TITLE
When selecting a month with more weeks than the current month, the time picker gains unexpected whitespace.

### ISSUE THREAD

**Issue by atelic** [Hacker0x01/react-datepicker#1596]
### Expected behavior
I expect the time picker to fill in space when the height of the container grows.
### Actual behavior
The time picker maintains empty whitespace until I scroll the area. 
### Steps to reproduce
1. Go to https://reactdatepicker.com
2. Open the Select Time demo to February 2019. 
3. Use the next arrow to navigate to March 2019.
4. See the whitespace

<img width="883" alt="screen shot 2018-12-31 at 9 47 17 am" src="https://user-images.githubusercontent.com/8905795/50562352-3f425f00-0ce1-11e9-9d23-66b90cabf11e.png">
<img width="883" alt="screen shot 2018-12-31 at 9 47 25 am" src="https://user-images.githubusercontent.com/8905795/50562354-41a4b900-0ce1-11e9-8567-2f1f2aa07c43.png">

**Comment by PaulRBerg** [comment]
In my case, this also happens when using the portal version.

<img width="1098" alt="Screen Shot 2019-04-19 at 15 19 11" src="https://user-images.githubusercontent.com/8782666/56429071-7ef57c80-62b9-11e9-99bf-67f1a10ec402.png">

 I'm not doing any special customisation to the height of the time container.

**Comment by PaulRBerg** [comment]
I'm not sure but #1297 could have something to do with this issue.

**Comment by PaulRBerg** [comment]
Issue fixed in #1717.
