### ISSUE TITLE
size of month container

### ISSUE THREAD

**Issue by Sim3Xx** [Hacker0x01/react-datepicker#1786]
### Expected behavior
Hello,
how do i reproduce the Calender Size of your Demosite? (https://reactdatepicker.com/)

The Calender is somehow much smaller than in shown in your demo :( 

------------------------------
Behavior on your site
![image](https://user-images.githubusercontent.com/46575728/59518820-ce75b480-8ec6-11e9-967f-96b32046e0da.png)
------------------------------
behavior on my site
![image](https://user-images.githubusercontent.com/46575728/59518885-f533eb00-8ec6-11e9-9e97-6ca571de6576.png)
------------------------------
my Code: 
![image](https://user-images.githubusercontent.com/46575728/59519053-522fa100-8ec7-11e9-8d47-0545333a8744.png)
Thanks for helping
------------------------------

**Comment by mckelveygreg** [comment]
I'm trying to adjust the size of mine, but I do know that is all sized with `rems`, so check what your `html {font-size: ...}`
I would still like to know how to adjust the size of just the picker since I can't adjust my html font-size...

**Comment by rajma996** [comment]
I was facing a similar issue. Adding the scale transformation worked for me.
I had added `transform: 'scale(1.5) translate(35px, 25px)`

**Comment by tonila** [comment]
Hi,

I have similar issue. I solved it by taking copy of default styles and changed rems to pixels.

**Comment by emilytimer** [comment]
> I was facing a similar issue. Adding the scale transformation worked for me.
> I had added `transform: scale(1.5) translate(35px, 25px)`

It worked in a blured way, I guess we could find a better way.

**Comment by jaure96** [comment]
I have overwritten the style, adding the zoom property to the react-datepicker class.
`.react-datepicker {
   zoom: 175%;
}`

**Comment by peterkrieg** [comment]
<img width="877" alt="Screen Shot 2021-04-28 at 5 00 13 PM" src="https://user-images.githubusercontent.com/7385488/116482845-f7518980-a853-11eb-9a1c-a2619130b0f3.png">

FYI to others ^ `zoom` not supported by firefox at time of my comment, and not considered standard.  I ended up going with `transform: scale(1.3)` which is a pain  since the browser doesn't resize the element.  It would be nice if the library evenually had something like a `scale` prop to control the sizing
