### ISSUE TITLE
Error with YYYY in date-fns v2

### ISSUE THREAD

**Issue by iop280** [Hacker0x01/react-datepicker#1789]
https://github.com/Hacker0x01/react-datepicker/issues/1767

- Issue still persists in 2.7.0 from clean node_modules install

**Comment by wparam** [comment]
+1

**Comment by caub** [comment]
This problem is particularly annoying

1. It's rarely a god idea to use an alpha version (date-fns v2.alpha https://github.com/Hacker0x01/react-datepicker/blob/master/package.json#L103)
2. the code is using `format(parsedDate, dateFormat, { awareOfUnicodeTokens: true })` without giving a possibility to opt out of this new formatting options https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md. (While I agree moment format is not standard, it's important to let users the possibility and time to migrate more gradually)

**Comment by modemmute** [comment]
Problem persists in 2.8.0. This error makes this library unusable until it's fixed. ☠️
Error: RangeError: Use `yyyy` instead of `YYYY` for formating years

**Comment by askesis** [comment]
+1

For now I ought to use the 2.4.... version of this package

**Comment by YuriScarbaci** [comment]
+1
Still a problem in version 2.9.6
version 2.4.0 works as intended
