### ISSUE TITLE
Date displaying issue with different time zones

### ISSUE THREAD

**Issue by mahender-vutkuri** [Hacker0x01/react-datepicker#2043]
In our project, we are using moment.js to convert the dates between the multiple time zones. We are using react-datepicker to select date. This picker is working fine when i choose IST(Indian Standart Time) or KST(Korean Standart Time) but the same is not working when i select PST(Pacific Standart Time).

**To Reproduce**

1. Create a date field with react-datepicker
2. Pass a sample date string to the react-datepicker (assume you are in IST,if you are passing 21-08- 
     2020 it will show the correct date)
3. Change the timezone to PST and do the same step again.Now it will show 2 days previous date, when you try to edit the date.

**Expected behavior**
Irrespective of the timezone, it should display the date that we have passed.

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [latest]

**Comment by kortik425** [comment]
Is there any good tip for this?

**Comment by bipindubey-technoark** [comment]
I am also facing same issue with react-datepicker.
i have selected 12:00 Pm in datepicker and i also console log it .... it shows Thu Jul 09 2020 12:00:00 GMT+0530 (India Standard Time) which is right time.
but when i click on save then it sends wrong time (2020-07-09T06:30:00.454Z).
It should send (2020-07-09T012:00:00.454Z)----Expected Behaviour
i dont know what is the issue and how to fixx this
