### ISSUE TITLE
Ability to hide non-included times

### ISSUE THREAD

**Issue by jaypatel512** [Hacker0x01/react-datepicker#2056]
**Is your feature request related to a problem? Please describe.**
We use this date time picker to present available time slots for customer to schedule appointment. Most businesses have start time and end time around business hours. We use includeTimes to provide only specific times that are available for booking. However, all the times starting from 12:00 AM - 11:30 PM are shown as disabled.

**Describe the solution you'd like**
Ability to set a boolean to `hideDisabledTimes` or similar to only show times that are available. 

**Describe alternatives you've considered**
Optionally, allow us to set startTime and endTime such a way that it removes all entries before and after them.

**Additional context**
<img width="1152" alt="Screen Shot 2020-02-16 at 10 16 01 PM" src="https://user-images.githubusercontent.com/1309895/74623457-553ff880-510a-11ea-97f6-528a775d75ba.png">

**Comment by muasir** [comment]
This feature will be very useful in mobile view.

**Comment by mnsr** [comment]
A workaround is using css.

`react-datepicker__time-list-item--disabled` is the css class used. Just set it to `display: none;`

**Comment by jaypatel512** [comment]
That worked. @mnsr Can this be made into a property that we can set ? I am new to javascript and react, probably with some help I can create a PR for it.

**Comment by mnsr** [comment]
Yes, it's possible to add another property, but I don't see any point in it. In time.jsx, line 108, it adds the disabled class. So if you had a hide prop, you'd just apply a new disabled-hidden (or whatever you want to call it) class. 

Overriding the style in your site's stylesheet is just more practical. Realistically, you'd be customising the calendar to match your website's look and  feel, so you'd be overriding the styles anyway. I personally feel that props should be reserved for actual functional stuff, rather than trivial style things.

But i'd encourage you to clone it and play around with the code if you want to use it as a learning experience.

**Comment by jaypatel512** [comment]
I agree with your comments @mnsr . Allowing people to pass visually customizing features as css properties, and keeping the props for functional stuffs only would make it easy to separate the two.

I would definitely love to document these classes at one point to make it obvious for newbies to identify such capabilities easily.

**Comment by jaypatel512** [comment]
Closing this comment as resolved.

**Comment by jovana** [comment]
When setting:

```
        minTime={setHours(setMinutes(new Date(), 0), 9)}
        maxTime={setHours(setMinutes(new Date(), 30), 18)}
```
It gives a list of eanbled time slots from 9 (am) to 18 (6pm). before an after are disabled. Using the workaround on display: none remove them from the list.

Now I want to block certain time slots:
```
        excludeTimes={[
          setHours(setMinutes(new Date(), 0), 11),
          setHours(setMinutes(new Date(), 30), 11),
          setHours(setMinutes(new Date(), 30), 17),
          setHours(setMinutes(new Date(), 30), 16),
        ]}
```
But this got removed as well because of the display:none css. 
So I would like (a workaround) to have a start and end time, but disable time inside the start - end time.

**Comment by srstomp** [comment]
> When setting:
> 
> ```
>         minTime={setHours(setMinutes(new Date(), 0), 9)}
>         maxTime={setHours(setMinutes(new Date(), 30), 18)}
> ```
> 
> It gives a list of enabled time slots from 9 (am) to 18 (6pm). before and after are disabled. Using the workaround on display: none remove them from the list.
> 
> Now I want to block certain time slots:
> 
> ```
>         excludeTimes={[
>           setHours(setMinutes(new Date(), 0), 11),
>           setHours(setMinutes(new Date(), 30), 11),
>           setHours(setMinutes(new Date(), 30), 17),
>           setHours(setMinutes(new Date(), 30), 16),
>         ]}
> ```
> 
> But this got removed as well because of the display:none css. So I would like (a workaround) to have a start and end time, but disable time inside the start - end time.

@jovana Almost a year ago, but you could use the timeClassName prop
