### ISSUE TITLE
Question: way to navigate the calendar to day selected.

### ISSUE THREAD

**Issue by bvelasquez** [Hacker0x01/react-datepicker#2081]
No problem or feature request. Curious if I can force the calendar to navigate to the month of the day selected. This is for an inline fixedHeight calendar. When I set a new date/time, the calendar remains on the currently selected month. Is there a way to force it to navigate?

Thank you.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by josiahmonks** [comment]
Just to clarify--- You are updating the date value from an external source, and wanting to the inline calendar to update dynamically?

**Comment by bvelasquez** [comment]
Yes. When I update my state that sets the calendar's "selected" property. The selected date is properly selected. However, because I'm setting it months in advance, the calendar doesn't navigate to that date after being set, but stays where I've navigated.

**Comment by eugenesaur** [comment]
@bvelasquez

I have a similar problem. I'm using this plugin as a full-year (1) and three-month (2) inline calendar. I need to change years (1) or months (2) and show search results for selected dates range - year or month (without manual date selection).

My solution was:


```
import { startOfYear, getYear } from 'date-fns';
...

    const [ startDate, setStartDate ] = useState(new Date());

    const [ yearStartDate, setYearStartDate ] = useState(startOfYear(new Date()));

    const handlePrevYearClick = () => {
        setYearStartDate(startOfYear(new Date(getYear(yearStartDate) - 1, 1, 1)));
    };

    const handleNextYearClick = () => {
        setYearStartDate(startOfYear(new Date(getYear(yearStartDate) + 1, 1, 1)));
    };

...

return (
<>
    <div className={"year-calendar-navigation"}>
        <button type={"button"} onClick={ handlePrevYearClick } />
        <button type={"button"} onClick={ handleNextYearClick } />
    </div>

    <DatePicker
        selected={ startDate }
        onChange={ date => setStartDate(date) }
        monthsShown={ 12 }
        inline

        openToDate={ yearStartDate }
        forceShowMonthNavigation={ true }
        fixedHeight
    />
</>
)

```


(I can't use renderCustomHeader with callbacks, because it will render only single block for single month.)

So, there are buttons with onClick-callbacks and local state changing.
New state will re-render datepicker.

For your case, you can change "openToDate" in your side-effect callback. But keep i mind, that this solution working slowly than native month change. 

Hope I understand you correctly and help)
