### ISSUE TITLE
Cannot read property 'componentNode' of undefined

### ISSUE THREAD

**Issue by dmezei** [Hacker0x01/react-datepicker#2082]
**Describe the bug**
When DatePicker component is set to open={false} and down/up keyboard keys are pressed in the input field the following error is thrown:
`Uncaught TypeError: Cannot read property 'componentNode' of undefined`

**To Reproduce**

1. Go here: https://codesandbox.io/s/distracted-montalcini-0tzfh
2. Click on the date input
3. Press up/down arrows

**Expected behavior**
No error thrown

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version 80

**Comment by sk91swd** [comment]
I have encountered the exact same issue in my project. The calendar widget is set to open={false} due to accessibility issues. I want keyboard/screenreader users to only type the date (ddmmyyyy) instead of using the widget. While testing I encountered this issue, that if the 'open' property is set to 'false', upon pressing the up or down arrow key the same "Uncaught TypeError: Cannot read property 'componentNode' of undefined" error is thrown. I was testing keyboard navigation, now I can only use the tab key to navigate away from the input field, which is ok.
Is there a fi for this error message?

**Comment by kurochkinSergei** [comment]
Having same issue

**Comment by Salman-13** [comment]
Having same issue. Solved by intercepting "ArrownDown" and "ArrownUp" actions and attaching e.stopPropagation() to them: 
`const onKeyDownDate = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      e.stopPropagation()
    }
  }`

**Comment by mztnnrt** [comment]
I also having the same issue, my defensive solution is here.

```css
.react-datepicker-popper {
  display: none;
}
```
