### ISSUE TITLE
ui is sometimes mixed up with other components..

### ISSUE THREAD

**Issue by littlehome-eugene** [Hacker0x01/react-datepicker#2083]
**Describe the bug**

I'm using it with react-native-web and when the ui gets drawn under the input, it looks like 

<img width="266" alt="Screen Shot 2020-03-11 at 11 28 24 PM" src="https://user-images.githubusercontent.com/24217396/76427735-08410080-63f0-11ea-8a1b-2c42e362d8e7.png">

whereas it looks fine when the ui gets drawn above the input like below

<img width="260" alt="Screen Shot 2020-03-11 at 11 28 37 PM" src="https://user-images.githubusercontent.com/24217396/76427841-37577200-63f0-11ea-8984-00f0b18c3060.png">

**To Reproduce**
```

 import DatePicker from 'react-datepicker'
 import "react-datepicker/dist/react-datepicker.css";

           <DatePicker
             selected={Date.parse(values.available_to)}
             dateFormat="yyyy-MM-dd"
             onChange={val => {
               setFieldValue('available_to', val);
             }}
           />
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: mac
- Browser chrome 
- Version ^2.13.0"

**Additional context**

**Comment by JofBigHealth** [comment]
@littlehome-eugene The issue is that react-native-web sets `z-index: 0` on all views in order make a new stacking context for each component. This means that react-datepicker's popup (z-index: 1) will render over the components in that view but under all subsequent components.

You have a variety of options for fixing this. For us, we use an override in our index.html file along with setting a z-index for a custom class option for the date picker:

```
<style>
    * {
      // WARNING! This breaks the stacking in RNW!!!
      z-index: auto !important;
    }
</style>
```

This is a somewhat nuclear option, but it works ok for us because z-index is banned in our codebase and we don't use any other third party libraries (at least on web).

I longer-term solution will be to use react-datepicker in inline mode and render it in a custom portal which can handle click coordinates, scroll and so-on to keep the menu in place. There's quite a few third party libraries that do that.
