### ISSUE TITLE
Allow custom dates

### ISSUE THREAD

**Issue by cristicismas** [Hacker0x01/react-datepicker#2158]
**Is your feature request related to a problem? Please describe.**
In my datepicker field I would like to have the ability to skip date check, or to allow some custom text instead of a date.

**Describe the solution you'd like**
For example, I want my users to be able to type 'Present' in the date field, and the datepicker would then simply return 'Present' instead of trying to convert it to a date.

I've tried using custom input to display the 'Present' text, and an onChange prop on the DatePicker to make the date 'Present', but I get an error when I select the Present date:

```
RangeError: Invalid time value
```

Is there already a solution for this?

**Comment by 3bOONAL** [comment]
> **Is your feature request related to a problem? Please describe.**
> In my datepicker field I would like to have the ability to skip date check, or to allow some custom text instead of a date.
> 
> **Describe the solution you'd like**
> For example, I want my users to be able to type 'Present' in the date field, and the datepicker would then simply return 'Present' instead of trying to convert it to a date.
> 
> I've tried using custom input to display the 'Present' text, and an onChange prop on the DatePicker to make the date 'Present', but I get an error when I select the Present date:
> 
> ```
> RangeError: Invalid time value
> ```
> 
> Is there already a solution for this?

Hello, for similar behavior I can recommend you use https://reactdatepicker.com/#example-inline-version with your Input component, so you can set any behavior to your input, but then you will transfer received value to Datepicker. For example, in input user wrote 'Present', then your function parses it to Date.now() and transfers it to DatePicker. I implemented something like that and it worked like a charm, so you don't have to rely on the package.

 I think described behavior is impossible to implement, because of many variants handle input data from users of the package.
