### ISSUE TITLE
How to customize left position of popper arrow

### ISSUE THREAD

**Issue by samir-m** [Hacker0x01/react-datepicker#2183]
I am unable to set a custom popper arrow position. Could anyone suggest to me?
![datepicker](https://user-images.githubusercontent.com/18673317/84487757-da07e100-acbc-11ea-8b08-19934a628455.PNG)

**Comment by tmatiev-inostudio** [comment]
```
popperModifiers={{
    arrow: {
      element: 'react-datepicker__triangle',
      fn: (data) =>
        Object.assign({}, data, {arrowStyles: null}),
    },
}}
```

**Comment by GarrickBrown** [comment]
The popper arrow can be positioned using the modifiers stated in the Popper docs https://popper.js.org/docs/v2/modifiers/arrow/. These have been updated since the last comment to be an array of modifiers. To ensure the arrow doesn't go beyond the border radius, add the following:
popperModifiers={[
  {
    name: 'arrow',
    options: {
      padding: 10, // 10px from the edges of the popper if the centre of the reference input is beyond the edge of the popper
    },
  },
]}
