### ISSUE TITLE
Today button not keyboard navigatable

### ISSUE THREAD

**Issue by hildersen** [Hacker0x01/react-datepicker#2383]
The today button isn't added to the tab order and is therefore unavailable through keyboard navigation. I'm using version 3.1.3.

To reproduce: 
1. Create a <Daypicker> with todayButton='today' set.
2. Attempt to navigate to Today button with keyboard. 
(You can test this in the Documentation example: https://reactdatepicker.com/#example-today-button )

Expected behavior: 
You can navigate to and select the Today button without using a mouse. 

Have made a workaround for this by adding a custom Today button as a child of <Datepicker>.

**Comment by mellis481** [comment]
Interestingly the Today button isn't a button at all which is the reason it's not keyboard accessible. It's a `<div>` with (I assume) an onClick handler.

![image](https://user-images.githubusercontent.com/39313898/221865495-a4d027c9-3c1d-4d09-b812-14748492af28.png)

Since this is just really bad, I can only assume a PR would be accepted for this which properly implements the today button with an actual HTML button. @martijnrusschen Is this true?
