### ISSUE TITLE
DatePicker position  issue 

### ISSUE THREAD

**Issue by JasperChang0525** [Hacker0x01/react-datepicker#2425]
Hi anyone can help me solve this issue?
Where is I zoom the computer's screen to more than 100%, the date picker position will run away from the label.

**Comment by JasperChang0525** [comment]
I set the orientation for the datepicker is bottom left auto
cause i want to display it above the label
var selectDate = $(context.previousDateNode).datepicker({
                container: context.fromRenderNode,
                orientation: "bottom left auto", 
                autoclose: true,
                format: "dd-M-yyyy",
                endDate: oneDayBefore,
                // widgetPositioning:{
                //     horizontal: 'auto',
                //     vertical: 'bottom'
                // },

**Comment by anupamhore** [comment]
i am facing the same issue. Mordern browsers allows zoom to go more than 100%. So i adjusted the zoom level of my application div. Rest of all the things work fine accept this datepicker. Its position changes and goes to other location in the screen. Any ideas to fix it so that it can stick to the desired location
