### ISSUE TITLE
Bug report: Choosing the min possible date highlights prev and new value

### ISSUE THREAD

**Issue by llyt** [Hacker0x01/react-datepicker#2471]
**Describe the bug**
DatePicker component receive props:

- selected
- minDate
- inline

when choosing the min possible date, prev and new value highlighted

**To Reproduce**

1. Go to [Example site](https://reactdatepicker.com/)
2. Click on **Min date** example
3. Add `inline` prop to DatePicker component
4. Choose min possible date in calendar.
5. See error

**Expected behavior**
At the moment when the minimum date is selected, the highlighting of the selected item is expected to switch.

**Screenshots**
![1603230609092](https://user-images.githubusercontent.com/43233552/96648296-ce49bc80-1337-11eb-8015-fb3dc1127adf.png)

**Possible Solution**
In `setSelected` method delete condition that check `!this.props.inline`. But this decision is head-on, and does not take into account the purpose of the existence of this check.

**Comment by panta82** [comment]
I believe the bug is here:
https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L566

The lib is using `isAfter()` from `date-fns` to check if date is valid for keyboard navigation. However, that doesn't seem to allow dates to be equal (eg. if both dates are truncated to day).

Temporary mitigation is to set `maxDate` as well (eg. far off into the future). That will cause the lib to use `isDayInRange()` path, which works correctly.
