### ISSUE TITLE
Calendar jumps to date by American formatting, regardless of Locale

### ISSUE THREAD

**Issue by Smoothsmith** [Hacker0x01/react-datepicker#2501]
As you type into the input box, the calendar 'jumps' to the date as you enter it in an inconsistent manner (Jumping between the American format and the provided dateFormat as you type).

(Context: My dateFormat is set to dd/MM/yyyy for this example, and locale to 'en-GB')
e.g. Today (27th October 2020), if I start typing I get the following results:

(Example 1)
5: 5th October 2020 (Correct)
5/: 1st May 2020 (Wrong)
5/7: 7th May 2020 (Wrong)
5/7/20: 7th May 2020 (Wrong)
5/7/2020: 5th July 2020 (Correct)

(Example 2)
05/: 5th October 2020 (Correct)
05/07: 5th July 2020 (Correct)
05/07/2: 7th May 2020 (Wrong)
05/07/20: 5th July 2020 (Correct)

```
import enGB from 'date-fns/locale/en-GB';
registerLocale('en-GB', enGB);

...

<DatePicker
      dateFormat="dd/MM/yyyy"
      portalId="root-portal"
      locale={'en-GB'}
    />
```

If the locale is set to en-GB, I would not expect any of these strings to jump to May (Even without the custom dateFormat provided).

Since I can only set the one format, and have set the locale, I'm not sure what else I can try to work around the problem.

**Comment by uhef** [comment]
I managed to work around this problem by using the `strictParsing` mode: https://reactdatepicker.com/#example-strict-parsing

Caveat here is that the calendar does not try to guess the selected date while typing at all, so it doesn't update until the date is written in its full format at which state it selects the correct date.

In my case this was better than the calendar selecting invalid dates while typing so I went with this.

Naturally it would be best if the calendar would be able to do some guesswork of partially entered dates but so that the guesswork would be based on the set locale, not on `en-US`.
