### ISSUE TITLE
Bad datepicker display for specific timezone

### ISSUE THREAD

**Issue by cedricfarinazzo** [Hacker0x01/react-datepicker#2525]
**Describe the bug**
The datepicker is not render properly for specific timezone (here: America/Havana).

**To Reproduce**

1. Change your browser timezone to America/Havana (add-on for firefox: [Change Timezone (Time Shift)](https://addons.mozilla.org/en-US/firefox/addon/change-timezone-time-shift/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
2. Go to [https://reactdatepicker.com/](https://reactdatepicker.com/)

**Expected behavior**
Datepicker normal display

**Screenshots**
![2020-11-06-142641_391x329_scrot](https://user-images.githubusercontent.com/34288081/98371288-31c43180-203c-11eb-95aa-a35cb5b6272b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version: 82.0 (64-bit)

**Comment by e1himself** [comment]
I had the same issue. But figured that it's not the timezone per se causing it, but changing the timezone with the Firefox extension. 

When I use the extension to change the timezone (even if it's the same one I currently have on my machine) -- the issue is there. But when I disable the extension, it's fine. 

:shrug:
