### ISSUE TITLE
Date Range with time 

### ISSUE THREAD

**Issue by ankiycode** [Hacker0x01/react-datepicker#2529]
Need help to implement date range with time, After enabling **"showTimeSelect"** I am able to select a time from the list but I need to disable past time value from the list.

**Comment by ndanvers** [comment]
https://reactdatepicker.com/

Scroll down to "filter times" and you should see a reference to what you'll need to remove some time input values

**Comment by ankiycode** [comment]
> https://reactdatepicker.com/
> 
> Scroll down to "filter times" and you should see a reference to what you'll need to remove some time input values

not working

**Comment by Kronos66** [comment]
Hi @ndanvers, @martijnrusschen   I found a problem why this is not working. I have the same problem because in npm/yarn we have a version without this commit:
`c6bbd1091a4478a918ab3e7fb921baa7d15cb16d` in this commit you bind selected day to filtering function, which this solution helping to filter time correctly. Could you publish a version with this fix? Thank you.
