### ISSUE TITLE
Keyboard Navigation for year and quarter pickers

### ISSUE THREAD

**Issue by timothy-adamson** [Hacker0x01/react-datepicker#2535]
**Is your feature request related to a problem? Please describe.**
Currently I am using the year and quarter pickers but need to implement a custom solution for keyboard navigation.

**Describe the solution you'd like**
Behaviour should be in line with the date picker, allowing tab to the current year/quarter and arrow keys to navigate between items.

**Describe alternatives you've considered**
I have attempted to implement keyboard navigation using keyboard event listeners and calling element focus methods.

**Comment by ThereseSande** [comment]
We are having the same issue here. We are using the year and quarter picker. 

To choose a year you have to press the tab button twice, and the years are presented in 2 columns where you can only navigate left and right and not up and down. 

For the quarter picker the issue is as described over here. 

You can also experience to "get stuck" on the quarter picker, as tabbing only sends you back and forth on the year bar.
