### ISSUE TITLE
Selected date keep showing in all months

### ISSUE THREAD

**Issue by toannguyen5597** [Hacker0x01/react-datepicker#2565]
**Describe the bug**
I choose a day **2020/10/25**, then all months have highlighted the day 25

**Screenshots**
![image](https://user-images.githubusercontent.com/49229534/100868595-65c13400-34ce-11eb-8876-235c3d7203fc.png)
![image](https://user-images.githubusercontent.com/49229534/100868625-6e196f00-34ce-11eb-8c14-bd6c517e80d8.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version 3.3.0

**Comment by eamiralian** [comment]
I'm also seeing this behavior

- OS: Windows 10
- Browser: Chrome
- Version 4.1.0

**Comment by gforro** [comment]
I can report this problem also. Is this a designed feature or a feature by accident (bug)?

**Comment by CarpenterJoseph** [comment]
Same issue for me

**Comment by Akridian** [comment]
Faced this issue too.

**Comment by zeus0123** [comment]
Try Removing adjustDateOnChange prop. This fixed for me

**Comment by leesharon** [comment]
A solution that worked for me was setting the minDate to null after the user clicked on next month. When the minDate is null this problem doesn't happen for me. the problem is that the Datepicker component doesn't auto rerender when setting the minDate to null so we need to do it manually and as well save the chosen date.

  /*
 This set of code addresses a known bug in react-datepicker where the selected day remains visually selected when changing months.

 To circumvent this, we are dynamically setting the minDate prop to null when the user navigates to a different month, effectively deselecting the previously selected day.

 However, react-datepicker doesn't automatically re-render when we update the minDate state, so it doesn't immediately reflect the updated prop.

 To force a re-render of react-datepicker, we generate a new key each time the month changes and apply it to the DatePicker component.
 This new key causes React to create a new instance of the DatePicker, reflecting our updated minDate prop.

 Since react-datepicker doesn't provide a method to programmatically navigate between months, we maintain our own state variables for the current month and year
 and construct a selected date in the current month. This makes the DatePicker display the month we want, without highlighting any specific day in the month.

 Note: This is a workaround solution to address the current limitations of react-datepicker. In future versions of the library,
 there might be more straightforward solutions, so please check the library's documentation if it's significantly past the last update of this code (June 2023).
*/

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const [minDate, setMinDate] = useState<null | Date>(new Date(today));

  const [key, setKey] = useState(Math.random().toString());
  const [displayMonth, setDisplayMonth] = useState(today.getMonth());
  const [displayYear, setDisplayYear] = useState(today.getFullYear());

  const saveMonthAndYearAndForceReRenderOfDatepicker = (date: Date) => {
    setDisplayMonth(date.getMonth());
    setDisplayYear(date.getFullYear());
    setKey(Math.random().toString());
  };

  const handleMonthChange = (date: Date) => {
    if (date.getMonth() > (chosenPickupDate?.getMonth() || 0)) {
      setMinDate(null);
      saveMonthAndYearAndForceReRenderOfDatepicker(date);
    } else {
      setMinDate(new Date(today));
      saveMonthAndYearAndForceReRenderOfDatepicker(date);
    }
  };
  const selectedDate = new Date(displayYear, displayMonth, 1);
  // *********************************************************************************************
  
  <DatePicker
        key={key}
        selected={selectedDate}
        onChange={onChange}
        locale={currentLanguage}
        monthsShown={isMobile ? 1 : 3}
        startDate={chosenPickupDate}
        endDate={chosenReturnDate}
        excludeDates={getExcludedDatesFromCurrentLocation()}
        selectsRange={!openPickupChooseDate}
        inline
        onMonthChange={handleMonthChange}
        minDate={chosenPickupDate || minDate}
      />

**Comment by danOstrata** [comment]
If you want to maintain keyboard navigation (which you should), you can override the default css:

`.react-datepicker__day.react-datepicker__day--keyboard-selected {
  background-color: transparent !important;
}

.react-datepicker__day--keyboard-selected:focus-visible {
  background-color: red !important;
}`

**Comment by AsadAlihp** [comment]
for anyone having this issue, you can pass

`disabledKeyboardNavigation`

prop this fixed the issue for me.

**Comment by marinaBRG** [comment]
Still hapenning.

**Comment by piotr7109** [comment]
Issue is still here for me in the version `8.1.0`
