### ISSUE TITLE
Week numbers not applied correctly

### ISSUE THREAD

**Issue by akoel** [Hacker0x01/react-datepicker#2572]
If "showWeekNumbers" prop is set to "true" the first week of 2020 should be the week of Sunday, Jan. 3. 2021. React datepicker says this is the 2nd week of 2021.

2020 should have 53 weeks, where the week ending on Jan 2, 2021 is the 53rd week. See: https://www.epochconverter.com/weeks/2021 as a reference for (official) weeknumbers. React datepicker seems to go only to 52 weeks.

**Comment by tonila** [comment]
I noticed this problem also.

**Comment by stephane-r** [comment]
Same for me.

But, i think the problem is with **date-fns**. This lib is used on **date_utils.js** file, and i've try this : 

`console.log(dfgetWeek(new Date())); // 2, it's wrong`

**Comment by 0xIvan** [comment]
Has this fix been released yet? When I go to the examples in the site and change locale to en-US and showWeekNumbers to true, it shows that week 1 starts on January 10th.

<img width="896" alt="Captura de pantalla 2021-07-06 a las 11 36 10" src="https://user-images.githubusercontent.com/83612730/124578410-7a8fec80-de4e-11eb-9831-93c46d7e1ae4.png">

**Comment by stebogit** [comment]
I noticed though that, for some reason, the locale value changes the week result.
Also noticed that the code still uses a locale value [here](https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L213), although it sohuld not matter at all since `date-fns/getISOWeek` only accepts [one date argument](https://date-fns.org/v2.23.0/docs/getISOWeek#syntax)

![Screen Shot 2021-07-23 at 1 04 35 PM](https://user-images.githubusercontent.com/12717225/126836200-e8d5fc1f-edf7-4669-aac1-60805ccfd241.png)

![Screen Shot 2021-07-23 at 1 04 47 PM](https://user-images.githubusercontent.com/12717225/126836202-4a495b24-1630-4c45-a259-5b368b226713.png)

`2021-07-23` should be W29 (source [wikipedia](https://en.wikipedia.org/wiki/ISO_week_date))
![Screen Shot 2021-07-23 at 1 05 40 PM](https://user-images.githubusercontent.com/12717225/126836205-404a4247-cad7-401e-98da-2ccf096423c6.png)
