### ISSUE TITLE
No time input icon on firefox or safari browser

### ISSUE THREAD

**Issue by kunalkp** [Hacker0x01/react-datepicker#2610]
**Describe the bug**
For Input time, the time icon is not visible on Firefox or Safari browser.

**To Reproduce**
1. Go on the official documentation to this particular example https://reactdatepicker.com/#example-input-time
2. Open the calendar and look at the time input box. No icon available to click and open time scroll.

**Expected behavior**
Time icon should be visible for all browsers.

**Screenshots**

Firefox:
<img width="892" alt="firefox" src="https://user-images.githubusercontent.com/8581665/103278110-ac804c00-49f0-11eb-9bb6-6ec6ecff9d6d.png">

Safari:
<img width="922" alt="safari" src="https://user-images.githubusercontent.com/8581665/103278121-b6a24a80-49f0-11eb-8dae-34f1cd46cf62.png">

Chrome (Works fine)
<img width="870" alt="chrome" src="https://user-images.githubusercontent.com/8581665/103278300-2dd7de80-49f1-11eb-9862-a069a04e58a0.png">

**Comment by gual** [comment]
Same issue on Firefox 85.0 (64-bit) Linux Mint

**Comment by jimbrewer1** [comment]
I understand that `DatePicker`'s `showTimeInput` is using the default browser html time input which is more advanced in Chrome than the other mentioned browsers.  The bug described above is in the browser implementation rather than `DatePicker`.

`showTimeSelection` uses a time selection that is rendered by `DatePicker`.
