### ISSUE TITLE
How to fully localise the datepicker?

### ISSUE THREAD

**Issue by liegeandlief** [Hacker0x01/react-datepicker#2703]
I need to fully localise the datepicker but the docs are not clear on how to do this. I am passing in the desired data-fns locale which handles a lot of the localisation but there are still a lot of labels which are in English e.g. the heading of the time selector when using `showTimeSelect` and the ARIA labels on many elements.

Please can you explain how to fully localise the component including all date and time UI elements and all accessible labels.

**Comment by michael-arvanitidis** [comment]
You could try passing in the props manually. It should definitely be handled by the localisation, but for the label saying "Time" when using the `showTimeSelect` prop you could use `timeCaption='something else'` to override it. I use the date picker with locale set to norwegian, but that only seems to affecth the name of days and months. 

I'm guessing you could use the react devtools to get the name of the props you are trying to translate and try sending them in yourself. This seems like a hacky workaround and should be fixed by localisation or documented. 

https://codesandbox.io/s/floral-river-07gcj?file=/src/App.js

**Comment by liegeandlief** [comment]
Thanks for the tip regarding `timeCaption`. It does seem that there are props which allow for localisation of various labels but they are not documented very well and so it is a bit of a guessing game knowing whether you have addressed them all. For instance `timeCaption` is not mentioned here https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md.

It would be good if the docs could be updated with a list of all the props available for localisation. I think it would also make more sense if all these things were passed as properties of one object rather than as separate props, although this would be a breaking change.

**Comment by alexeyr-ci2** [comment]
I'm happy I've run into this issue before trying to use the component. And some `aria-label`s don't seem to be localizable: https://github.com/Hacker0x01/react-datepicker/blob/346221d14c4d9cb3f42d80c5233060af4d3c9cd0/src/calendar_container.tsx#L15-L23
