### ISSUE TITLE
Is it possible to click on the year and month, show year and month picker? Similar to bootstrap-datepicker

### ISSUE THREAD

**Issue by flora8984461** [Hacker0x01/react-datepicker#2709]
**Is your feature request related to a problem? Please describe.**
I really love this library, but I could not find a way to click on year and month, then show year and month picker, similar to https://bootstrap-datepicker.readthedocs.io/en/latest/ or https://projects.wojtekmaj.pl/react-date-picker/ .

Thanks!

**Comment by schmitch** [comment]
yeah I think that would be an awesome feature. basically we migrated from boostrap-datepicker and that is the only thing we did not like that much.

**Comment by NOIPA171** [comment]
I had to manually change the types of picker to show up with each selection, so it's actually possible. You'd need a custom header to manage the switching of pickers, but a major problem with this is if you click on the months or years it selects the start of the unit instead of just updating the month or year, so with each onChange event I had to use moment to set the value of the unit, unless you don't mind that at all.
Another issue I had with this approach is that the package doesn't currently support year range picker, so the same logic becomes buggy when switched to the year panel in range pickers.
