### ISSUE TITLE
Keyboard accessibility when the showYearPicker prop is used.

### ISSUE THREAD

**Issue by jp-albrecht** [Hacker0x01/react-datepicker#2901]
**Is your feature request related to a problem? Please describe.**
There is no keyboard accessibility when the prop showYearPicker is used. If I tab to the component, I get stuck tabbing between the left and right navigation arrows.

**Describe the solution you'd like**
The same keyboard functionality that the normal DatePicker has would be great.

**Comment by ezulu** [comment]
This same issue exists when the showQuarterPicker is used. You can only tab between the left/right arrows.

**Comment by dgreene1** [comment]
I have a team of developers that would be willing to fix this if @martijnrusschen can clarify that a PR would be considered?

We would include automated testing with the PR.

**Comment by martijnrusschen** [comment]
Yes totally, all pull requests are welcome. Excited to make this work if someone is willing to put time into it.

**Comment by dgreene1** [comment]
Wonderful. If someone wants to take it on the meantime, feel free. We’ll report back once our product team approves the work.

**Comment by dgreene1** [comment]
@martijnrusschen I regret to inform you that our product manager / UX designer has chosen to only offer an Input (with year error validation) instead of a full year picker so we won't be able to work on this bug. But we will be using the rest of your wonderful library. We want to thank you and the community for your wonderful contributions and we will look for opportunities to help in other ways if/when the schedule allows.

**Comment by mellis481** [comment]
This issue should be closed as it's not an issue at all. It's the same focus lock technique that is implemented in the day picker version where tab gets locked between the calendar and the month controls. This is expected/desired functionality. If you want to break out of the focus lock, click enter (to make a selection) or escape (to not make a selection).
