### ISSUE TITLE
Locale RU does not work since version 4.*

### ISSUE THREAD

**Issue by Erfolg1982** [Hacker0x01/react-datepicker#3031]
When selecting the RU locale, the first day of the week is Sunday. It is impossible to change to Monday. In version 3.8 everything worked and since 4 it does not work anymore

<img width="1705" alt="ver3" src="https://user-images.githubusercontent.com/33613608/120895509-e7cd1980-c625-11eb-977c-37d159cf682c.png">

<img width="1705" alt="ver4" src="https://user-images.githubusercontent.com/33613608/120895534-0b905f80-c626-11eb-84e8-7610ae55ff0e.png">

**Comment by oleg-tsalabionak** [comment]
PR #3045 possibly fixes this issue

**Comment by Bulva** [comment]
It is because in the new version locale is not used for startOfWeek (https://github.com/Hacker0x01/react-datepicker/blob/60f1aa48e7e1116a54cfda1f0449f6c945250245/src/week.jsx#L92). I think it is definitely bug but there is a `this.props.calendarStartDay` used instead of locale value. In the new version you can set calendarStartDay props as a temporary solution:
```
<DatePicker
      calendarStartDay={1}
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      locale="en-GB"
      placeholderText="Weeks start on Monday"
    />
```
