### ISSUE TITLE
"disabled" is ignored if "inline" is set

### ISSUE THREAD

**Issue by toresbe** [Hacker0x01/react-datepicker#3047]
**Describe the bug**
If the inline prop is set, setting disabled has no effect.

**To Reproduce**
Create a page with DatePicker and set "inline" and "disabled".

**Expected behavior**
DatePicker stops reacting to events and appearance changes to indicate it is disabled.

**Additional context**
This is a duplicate of #2191 which was filed June 2020, and then auto-closed as stale in December.

**Comment by humphreyja** [comment]
Just a heads up, this is actually an expected behavior. [Here's the test that proves that](https://github.com/Hacker0x01/react-datepicker/blob/master/test/datepicker_test.js#L509)

What I suspect is going on here is that the actual calendar component does not have any sort of disabled functionality (normally it just doesn't show when it is disabled). Instead, I'd just ignore onChange events and give it a disabled class if you wanted to style it. This is likely not to change 🤷‍♂️
