### ISSUE TITLE
Escape key acts like enter key

### ISSUE THREAD

**Issue by TenPotatoes** [Hacker0x01/react-datepicker#3084]
1. Enter a partial date, decide not to do that, press escape
2. Partial date is parsed into a date the same as if you pressed enter. Ex: Enter 1 and press escape -> 01/01/2021

Some say escape should do nothing. I think it should revert to your previously valid value, like this one does https://ant.design/components/date-picker/

**Comment by dgreene1** [comment]
I think this should be reopened since it's still occurring and is a serious a11y problem.

**Comment by dgreene1** [comment]
I will say that our team will not likely be submitting a fix for this because we're solving this by separating our custom input from a button that spawns the react-date-picker calendar and then we're checking the event was an escape so we can keep the previous value.

By the way, our choosing to split off the date input from the calendar was partially motivated as a workaround for this escape issue, but also because we need a workaround to easily tap into using the Intl formatter instead of date-fns as is mentioned in https://github.com/Hacker0x01/react-datepicker/issues/4119
