### ISSUE TITLE
custom input ref

### ISSUE THREAD

**Issue by AlexSav94** [Hacker0x01/react-datepicker#3090]
**Is your feature request related to a problem? Please describe.**

It seems to me, that there is no way to get input ref at this moment.

**Describe the solution you'd like**

It will be useful, if we can get input ref simple like:

`
<ReactDatePicker ref={ref}/>
`

**Comment by samueldjones24** [comment]
hey @AlexSav94 , i've implemented a custom input using `forwardRef`:

```
const CustomInput = forwardRef((inputProps, ref) => {
        const { value, onChange } = inputProps
        return (
            <div>
                <StyledInput
                    value={value}
                    onChange={onChange}
                    placeholder='Pick a date'
                    ref={ref}
                />
            </div>
        )
    })

```

And then pop that into the DatePicker: 

```
<ReactDatePicker 
      customInput={<CustomInput />} 
/>

```

Hope this helps!

**Comment by benmarch** [comment]
I ran into this issue as well because I pass a ref into my DateInput component from the parent. Here's the pseudo code for my component that made this work:

```jsx
const DateInput = forwardRef((props, ref) => {
  const CustomInput = useMemo(() => props => <Input {...props} ref={ref} />, []) // <Input /> is my custom input component

  return (
    <DatePicker customInput={<CustomInput />} />
  )
})
```

Notice that I'm ignoring the ref that is passed to `CustomInput` and just forwarding the ref I care about. I'm not sure if this has negative affects on the DatePicker, though, because I'm managing the open/closed state with the `open` prop. It works perfectly this way, and the ref is properly passed.

If you notice issues, you can try replacing the CustomInput with this:

```jsx
// ref is from the parent
// customRef comes from DatePicker
// inputRef is passed to the custom input element and updates both the other refs when it changes
const CustomInput = useMemo(() => forwardRef((props, customRef) => {
    const inputRef = useRef()

    useEffect(() => {
      if (inputRef.current) {
        if (typeof customRef === 'function') {
          customRef(inputRef.current)
        }

        if (customRef.hasOwnProperty('current')) {
          customRef.current = inputRef.current
        }

        if (typeof ref === 'function') {
          ref(inputRef.current)
        }

        if (ref.hasOwnProperty('current')) {
          ref.current = inputRef.current
        }
      }
    }, [inputRef.current])

    return <Input {...props} ref={inputRef} />
  }), [])
```

It's really verbose, but it did appear to work in my basic test. Good luck!
