### ISSUE TITLE
bad days with two months displayed

### ISSUE THREAD

**Issue by nacimgoura** [Hacker0x01/react-datepicker#3250]
Hello, when I use the calendar by displaying 2 months (`monthsShown={2}`), there are random days that are displayed in the wrong place (see on the picture).
For info I use it in a CalendarContainer

**Screenshots**
![Screenshot from 2021-10-06 16-43-55](https://user-images.githubusercontent.com/9990521/136227411-25120299-c279-4503-ba29-51672f742c78.png)

**Desktop (please complete the following information):**
- Browser: Chrome

**Comment by nick-shmyrev** [comment]
Also seeing this issue, tested in Chrome 95 with package versions 3.4.1 and 4.3.0.

**Describe the bug**
When using `react-datepicker` with `fixedHeight` and `monthsShown={2}`, "extra" days are shown on the left calendar. Disabling `fixedHeight` fixes the issue.

**To Reproduce**
Steps to reproduce the behavior:

1. Render `react-datepicker` with `fixedHeight` and `monthsShown={2}` options.
2. Navigate left calendar to February 2021, March 2021, June 2021, August 2021 or November 2021.
3. Observe the issue


**Expected behavior**
Left calendar should either render next month dates starting from the 1st, or not render them at all.

**Screenshots**

<img width="444" alt="Screen Shot 2021-11-05 at 15 33 21" src="https://user-images.githubusercontent.com/6802396/140568434-da522d71-a19f-4c7e-8c1a-869f189a21fb.png">
<img width="444" alt="Screen Shot 2021-11-05 at 15 33 34" src="https://user-images.githubusercontent.com/6802396/140568435-ccc3a352-223c-4187-9786-be3340c4043a.png">
<img width="444" alt="Screen Shot 2021-11-05 at 15 33 47" src="https://user-images.githubusercontent.com/6802396/140568436-5cdbd48a-67bb-420d-90dd-3e010c5a8151.png">
<img width="444" alt="Screen Shot 2021-11-05 at 15 34 14" src="https://user-images.githubusercontent.com/6802396/140568437-58dcd777-9056-4527-a048-fab8eda67c25.png">
<img width="444" alt="Screen Shot 2021-11-05 at 15 34 28" src="https://user-images.githubusercontent.com/6802396/140568439-25cb5df2-210b-4def-aa1b-7c479c951e53.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 95
