### ISSUE TITLE
How to set Today

### ISSUE THREAD

**Issue by nsisodiya** [Hacker0x01/react-datepicker#338]
I want to show a different Today. Because my client can visit to any other country he want to see date as his actual today and not the today in the country he is present.
Any idea or hack how to do it ?

**Comment by nsisodiya** [comment]
I checked the code.
Instead of this
```js
"datepicker__day--today": this.isSameDay(moment()),
```

I suggest for having 

```js
"datepicker__day--today": this.isSameDay(this.props.today),
```

and you can set default value of today is `moment()` and user will be able to overwrite it.

**Comment by nsisodiya** [comment]
Generated Pull Request - https://github.com/Hacker0x01/react-datepicker/pull/339

**Comment by rafeememon** [comment]
Is it possible to use moment localizations so that the dates are always in the timezone that you specify?  I'm weary of adding this to the API of the datepicker and breaking the simple contract of today being "today."

**Comment by nsisodiya** [comment]
@rafeememon - instead of timezone, specifying today is much better approach just like `selected` prop. In my pull request, I have added this props as optional prop.

Also, there is no breaking because advance user want this behaviour. normal user will not pass `today` props. There is not a single date picker exist which provide this functionality. (Setting as custom today)

**Comment by rafeememon** [comment]
Understood that this is not a breaking change, but in general I would prefer to not add to the API, as we need to support it.  Can you explain why this approach is better than using localization?

**Comment by nsisodiya** [comment]
Because, If you want to pass timezone then you have to add moment-timezone library.
http://momentjs.com/timezone/ It is 25KB on gzipped.
I do not know, just for one simple task, why will we add another library specially this is a client side code.

`Can you explain why this approach is better than using localization`
I exactly do not understand this. `localization` has nothing to do with it. 
I made a pull request for API so that user can set a different today other than today as seen by the browser.

**Comment by rafeememon** [comment]
I think part of the job of software engineering is finding the right set of features that:

* makes common use cases easy
* makes advanced use cases **possible**

I think a big advantage of using the moment.js library is that we are able to leverage its plugins, like moment-timezone, making it unnecessary to duplicate its effects.  As we move towards a 1.0 release of the datepicker we're focusing on cleaning up the API, and I'm not convinced that the `today` prop belongs for this use case because you can use moment-timezone.  Keep in mind that once a prop is added, we need to support it long-term.

For your use case I suggest that you do one of the following:

1. Use moment-timezone
2. Override the `font-weight` style for `datepicker__day--today` so that it doesn't look different from other days, and possibly set `selected` to the date that you have in mind, or manually apply the bold style to whatever date you want

**Comment by nsisodiya** [comment]
Override the font-weight style for datepicker__day--today - Possible.
using selected prop for today -- Not Possible.
Because selected prop has different purpose.
May you show me how to do this - "manually apply the bold style to whatever
date you want"
Because, I do not think it is possible. I checked the rended html and there
is no way I can make any `selector`.

**Comment by rafeememon** [comment]
You can use a library like jquery to find `.datepicker__day--today` elements, inspect the day, and toggle the font accordingly.

I ***strongly*** recommend using moment-timezone here.

**Comment by nsisodiya** [comment]
@rafeememon - Your DatePicker is showing 9 Feb as Bold which is Today. I want to Bold 8 Feb which is my client's Today. 
With JavaScript or selector, I can toggle Bold for 9 Feb to look like normal date. But showing Bold on 8 Feb is not possible. That is my problem.

**Comment by rafeememon** [comment]
@nsisodiya, understood, but this is an example of the XY Problem.  You should use moment-timezone to accomplish what you're trying to do.
