### ISSUE TITLE
Parameterize z-index for tether-element

### ISSUE THREAD

**Issue by felizuno** [Hacker0x01/react-datepicker#375]
Hi, I'm very new to React so sorry in advance if I missed something.

My first time I tried to use this component was inside a takeover which uses an increased z-index, and so the `.datepicker__tether-element` appeared behind the takeover markup. It would be great to be able to pass z-index as a parameter so that style overrides are not required.

Like I said I'm new to React, but would be happy to try to do the work and send a pull request if you can point me in the right direction :-)

**Comment by rafeememon** [comment]
I'm hesitant to add something like this as we try to finalize an API for a v1.0 release because

* This potentially encourages bad programming practice by having z-indices appear in both CSS and Javascript
* The problem is solvable by adding a z-index to the tether element in CSS (assuming you already have a CSS solution set up, which is necessary to make the datepicker usable)

A potential solution here is to add a default z-index to the tether element (in the datepicker stylesheet) that will be good enough for "most" cases, but unfortunately there can't be a value that can cover all cases.  Let me know if I'm off on anything here.

**Comment by martijnrusschen** [comment]
I agree that added a parameter for this feels wrong. This is really a CSS thing and we should keep that in CSS. I just updated the datepicker in our own Codebase (since I just finished the upgrade to React 0.14) and I noticed that I had to add a z-index to the `.datepicker__tether-element` to make sure it didn't fall below other parts. (A z-index of 2 worked fine here.)

**Comment by serphacker** [comment]
Got same issue, fixed by adding a CSS with : 
```
.datepicker__tether-element {
    z-index: 2;
}
```

**Comment by felizuno** [comment]
The referenced PR resolves the core of my issue, which is really just that the default z-index is `1`, where it would be better to have it unset or set to an extremely high value e.g. #378. Given that change to the default style I am inclined to agree that adding a z-index parameter is a bad idea.

Closing this issue in anticipation of #378.
