### ISSUE TITLE
Rewrite usage of ReactDOM.render to React 18

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#4300]
> ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17.

Blocking https://github.com/Hacker0x01/react-datepicker/pull/4207 currently. See https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis for guidance on how to use the new render.

**Comment by martijnrusschen** [comment]
@frankops11 If you're looking for a nice challenge, there are 13 usages across 4 files in the code base. These need to be rewritten to the new React 18 way.

**Comment by frankops11** [comment]
Challenge accepted!🔍🛠️

**Comment by frankops11** [comment]
@martijnrusschen accepting the challenge has been quite an adventure. After making changes in 'docs-site' and 'examples', no issues arose; everything went smoothly. However, when we dove into the universe of unit testing, that's where the house came tumbling down, haha! Given that we are using Enzyme and, to this day, there is no support for React 18 nor anything official about it, many tests simply break, and honestly, I don’t know if you have tried to tackle something similar. One strategy that occurred to me was to migrate some of those tests to Testing Library, but I'd love to hear your thoughts on this.

![image](https://github.com/Hacker0x01/react-datepicker/assets/50973629/998f3c62-d6ce-467e-80cd-3e10d1090493)

**Comment by martijnrusschen** [comment]
It looks like the problematic part is the Enzyme adapter that's specifically for React 17. It looks like Enzyme and Jest go well together though: https://enzymejs.github.io/enzyme/docs/guides/jest.html. Can we get rid of the React 17 adapter?

**Comment by frankops11** [comment]
Thank you for pointing out the issue and providing additional resources 🙏. 

I've explored the [Enzyme's compatibility thread](https://github.com/enzymejs/enzyme/issues/2524#issuecomment-1116246491) and the article ["Enzyme is dead, now what?"](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl) to grasp the current situation with Enzyme, particularly concerning its compatibility with React 17 and the forthcoming versions.

It seems like the path forward with Enzyme is a bit murky 🌫️, especially considering the move towards `react-testing-library` by many in the community due to the uncertain future of Enzyme. The particular concern with React classes in future versions does pose a valid concern 🚧. 

Given the circumstances and for future-proofing our testing architecture, it might be prudent to explore alternative testing utilities that have clear support and roadmap with React's future versions. `react-testing-library` is a prominent candidate, but we must consider the refactoring costs and any testing paradigm shifts it may introduce 🔄.

I'd love to discuss and strategize on how we can smoothly transition our testing stack to align with the evolving React ecosystem while mitigating risks and ensuring that our testing suites remain robust and effective 🚀. 

Looking forward to collaborative thoughts and further discussions!

**Comment by martijnrusschen** [comment]
That's a good thought. We just moved the test suite from Karma to Jest which has been a major change already. I think that making it further future proof would definitely be a good move to make sure we don't need to change again in the future. We could try to remove Enzyme all together to see how many tests break so that we have an understanding of the impact and effort to make this happen. 

Pinging @Zarthus and @polbene95 for some input as well.

**Comment by martijnrusschen** [comment]
This document outlines how to migrate from Enzyme to RTL. Doesn't seem to be a major challenge looking at the minimal usage we have in the code base: https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/

**Comment by frankops11** [comment]
Yep, I'm on board with looking into ditching Enzyme. Just curious about the urgency level here - how fast are we wanting this done? I'm all in for contributing but just to set expectations, my time's a bit patchy during the week (full-time job things, you know). So, a big YES from me, and always happy for any help or tips from you all to make things zoom along! 🚗💨

**Comment by martijnrusschen** [comment]
156 occurrences of Enzyme left.

**Comment by martijnrusschen** [comment]
cc @yuki0410-dev

**Comment by yuki0410-dev** [comment]
@martijnrusschen
Thanks for your quick review and merge.
There are now only two more files that I have not refactored. (datepicker_test.test.js, calendar_test.test.js)
They are very long files and may take some time.
After they are done, I will start removing the little bit of Enzyme I have left.

**Comment by yuki0410-dev** [comment]
My thought is that after removing all Enzyme, that Linter may not be needed if the Enzyme is removed from package.json. (The Enzyme test will not be able to run itself.)

**Comment by martijnrusschen** [comment]
Agreed!

**Comment by martijnrusschen** [comment]
Enzyme has been removed completely now. Thanks to @yuki0410-dev!
