### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by Gywem** [Hacker0x01/react-datepicker#459]
I am getting the next errors on console when I am instantiating a `DataPicker` in the render method from my component.

`Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded`

Then when I click on the datapicker input, the dialog is shown, but I got:

`react-datepicker.min.js:7 Uncaught TypeError: Cannot read property 'jquery' of null`

and

`ReactErrorUtils.js:71 Uncaught TypeError: Cannot read property 'focus' of undefined`

I am running React v0.14.8. Do you have any idea why this is happening?

Thanks

**Comment by rafeememon** [comment]
What version of the date picker are you using?  Also please post the relevant code as it's very hard to tell what's going on without it.

**Comment by Gywem** [comment]
react-datepicker v0.25.0

Basically I have a custom component that uses DatePicker, imported as a ReactDatePicker.
``` javascript
import ReactDatePicker from 'react-datepicker';
// [...]
getInitialState: function() {
  return {
    startDate: moment()
  };
},
render() {
    const {
      labelText,
      disabled,
    } = this.props;

    let className = '';
    if (disabled) {
      className += ' disabled';
    }

    return (
      <label className={`field${className}`}>
        { labelText }
        <ReactDatePicker
          selected={this.state.startDate}
        />
        <br />
      </label>
    );
  },
```

And the callstacks of the errors:

![jqueryofnull](https://cloud.githubusercontent.com/assets/2581993/14810843/3e76fdba-0b95-11e6-841c-ee49db7d554d.png)
![focusofundefined](https://cloud.githubusercontent.com/assets/2581993/14810848/42285436-0b95-11e6-9688-9be8f03d62b8.png)

Thanks

**Comment by rafeememon** [comment]
How are you declaring your class?  If it's a functional component, it won't work because we use refs; you'll need to use `React.createClass` or `class Blah extends React.Component { ...`.

**Comment by rafeememon** [comment]
@Gywem, take a look at #334 and #136 as well (please search for this kind of thing in the future)

**Comment by hariram1975** [comment]
"npm ls react" will tell us the list of react component available in node_modules. I saw two version available, I deleted react folder from node_modules and did npm install again which solved my issue

**Comment by chestozo** [comment]
I was struggling with the same issue for a day.
So finally in my case it was 2 different versions of React inside `node_modules` but it was somehow difficult to reproduce it - sometimes `npm` would install only one version, another time - both.

```(sh)
$ npm ls react
my-mega-pack@0.1.0 /home/chestozo/my-mega-pack/client
├─┬ common-components@1.4.4
│ └── react@15.6.1
└── react@15.4.0
```

There are 2 types of fix as far as I could understand:

1) use same React version as your dependencies
In my case it was like on the snippet above - I had `react@15.4.0` and `react@15.6.1`.

This was because in my package.json I had `"react": "15.4.0"` while in dependency package `common-components` they had `"^15.1.0"`.
After changing version in my `package.json` to the same version as specified in `common-components` - `"^15.1.0"` - it was fixed.

2) another fix is to specify `resolve.alias` in webpack config (I am using webpack) - found here
https://stackoverflow.com/a/42411974/449345
https://stackoverflow.com/a/31170775/449345

Like this:
```
{
    resolve: {
        alias: {
            react: path.resolve('./node_modules/react'),
            'react-dom': path.resolve('./node_modules/react-dom')
        }
    }
}
```
Maybe it helps someone else.
