### ISSUE TITLE
Tether classPrefix missing?

### ISSUE THREAD

**Issue by webdesserts** [Hacker0x01/react-datepicker#475]
The dom for datepicker currently looks like the following when updating to 0.27.
![screen shot 2016-05-03 at 2 31 49 pm](https://cloud.githubusercontent.com/assets/916253/14996954/13693392-1142-11e6-8089-54b3ef4bd024.png)
Notice the missing `datepicker__` prefix on all tether classes. Is there anything I could be doing on my end that could be causing this?

**Comment by rafeememon** [comment]
Looks fine to me on the demo site:

<img width="410" alt="screen shot 2016-05-04 at 10 50 49 am" src="https://cloud.githubusercontent.com/assets/1829450/15010820/28da9280-11e6-11e6-9b77-1cf95ce5b14e.png">

Are you sure you're using v0.27?  It's been a couple versions since we had the `datepicker__container` class in the codebase.

**Comment by webdesserts** [comment]
@rafeememon Looks like some weird resolve stuff was going on with `npm link` everything looks good now 👍
