### ISSUE TITLE
Broken when used together with 5.x of react-onclickoutside

### ISSUE THREAD

**Issue by chodorowicz** [Hacker0x01/react-datepicker#483]
I'm using in my project latest 5.1.0, but it unfortunately conflicts with the one bundled with `react-datepicker`. When I downgrade to 4.x all starts to works.

You can see in this sample bin that when `react-onclickoutside` 5.1.0 is included in package.json webpack fails importing `react-datepicker`
http://www.webpackbin.com/EyiNOac-W

Locally I get following stacktrace
```
invariant.js?4599:38 Uncaught Invariant Violation: ReactClass: You're attempting to use a component class or function as a mixin. Instead, just use a regular object.
```
![image](https://cloud.githubusercontent.com/assets/119451/15150238/a773426e-16cc-11e6-8383-1ba6721baded.png)

I suppose webpack serves 5.x to datepicker what obviously fails, since their exports are not compatible.

Temporary solution: I've downgraded my local `react-onclickoutside` to 4.9

**Comment by rafeememon** [comment]
Yeah, the API of `react-onclickoutside` changed between v4 and v5.  As a workaround you can probably depend on `react-datepicker/lib/date_picker` instead, which doesn't automatically bundle `react-onclickoutside` and will be resolved by your module bundler instead.

**Comment by chodorowicz** [comment]
@rafeememon Thanks for quick response. But depending on `react-datepicker/lib/datepicker` doesn't soble the problem, fails in the same way. The problems is, I think, that when building `react-datepicker.min.js` `react-onclickoutside` is not bundled together and instead my top level 5.x is being used. And when depending `react-datepicker/lib/datepicker` datepicker of course tries to use wrong onclickoutside (5.x) and fails.
react-datepicker.min.js → http://pastebin.com/XeAZcRbj

**Comment by rafeememon** [comment]
I'm a little confused here because the when the datepicker is installed, it should recognize that the version of onclickoutside you use in your project isn't compatible, and it should install v4 under the datepicker's node_modules (because of the caret dependency).  Can you poke around your node_modules folder to see what is resolving to what, and maybe try a clean npm install of your entire project?

**Comment by chodorowicz** [comment]
So, yes, the v4 is installed inside `node_modules/react-datepicker/node_modules/react-onclickoutside`, but it seems the dist `react-datepicker` build doesn't have it included and (only `require("react-onclickoutside")` calls), so I when I run my final build with Webpack this require is resolved with v5 `node_modules/react-onclickoutside`... Maybe I have sth strange in my webpack config.

**Comment by rafeememon** [comment]
Yeah, in that case the dependencies are set up correctly and unfortunately I don't think there's anything else we can do on the `react-datepicker` end -- sounds like a question for webpack now.

As an aside, updating our version of `react-onclickoutside` is on the to-do list and a PR doing this would be welcome =)  There are some API changes that need to be sorted out but should be pretty straightforward.

**Comment by chodorowicz** [comment]
Cool, thanks! I might take a shot at PR when I find time.

**Comment by cdomigan** [comment]
I'm running into the same issue. Not sure why webpack wouldn't be picking up the correct dependency here? Anyone had any luck resolving this issue?

**Comment by tudorpavel** [comment]
I'm in a Rails context, so I had this issue because `react-onclickoutside` dependency was completely missing.

My problem was that `react-onclickoutside` is [defined in webpack](https://github.com/Hacker0x01/react-datepicker/blob/v0.30.0/webpack.config.js#L48) as an external dependency, so it's not bundled together with `react-datepicker`, it simply expects it to be available.

My solution was grabbing [index.js version 4.9](https://github.com/Pomax/react-onclickoutside/blob/v4.9.0/index.js) and adding it before `react-datepicker` in my Rails asset pipeline. 

That's it, problem solved. Just make sure a 4.x version of `react-onclickoutside` is available in your context.
