### ISSUE TITLE
Datepicker inside a modal

### ISSUE THREAD

**Issue by reyhansofian** [Hacker0x01/react-datepicker#488]
Hi, I have a datepicker inside a modal. Whenever I clicked on the date, the modal got closed too. Is there a way to avoid this? My code looks like this

```
import React from 'react';
import moment from 'moment';
import { change } from 'redux-form';
import DatePicker from 'react-datepicker';

class ReservationDetailsCheckinContainer extends React.Component {
  constructor(props) {
    super(props);
  }

  handleInputChange(e) {
    console.log(e);
  }

  render() {
    return (
      <div className="pull-left" style={{
        width: '65%'
      }}>
        <label>
          Check-in Date
        </label>
        <div>
          <DatePicker selected={this.state.startDate} onChange={this.handleInputChange}/>
        </div>
      </div>
    );
  }
}

export default ReservationDetailsCheckinContainer;
```

**Comment by TMUND** [comment]
Have you tried e.stopPropagation()?

**Comment by mezod** [comment]
Did you make anything special to make it work inside a modal? It doesn't work for me

**Comment by leojh** [comment]
Anyone find a solution to this?

**Comment by mayrsascha** [comment]
The problem here is that the onChange callback only provides the newly selected date, but not the event associated with it. If we would get the event as lets say second parameter the following code should work:

`handleInputChange(date, e) {  
    e.persist();  
    e.stopPropagation();  
  }`

It would work because AFAIK most modals are adding a click listener to window and then check if the click target (in our case the datepicker calendar) is the modal itself or a children of it.

BUT
React datepicker is using the tether library to connect the date input field with the calendar component and tether is placing the calendar outside the modal before the closing body tag for positioning reasons

<img width="585" alt="bildschirmfoto 2016-07-14 um 10 44 16" src="https://cloud.githubusercontent.com/assets/5527658/16834136/c478e616-49b2-11e6-8491-6d8c01ef57f8.png">

So technically the calendar is not inside your modal and thats why it closes. As I wrote already, exposing the React event in the onChange callback would probably solve this, since then you can stop the event from reaching the window onclick listener

**Comment by reyhansofian** [comment]
Yeah, you're right. Thanks for your answer

Reyhan Sofian
Web Developer

**Comment by LeoZeda** [comment]
Is there a way to get the event?

**Comment by kiddo13** [comment]
+1

**Comment by shanSyapse** [comment]
+1

**Comment by mateder** [comment]
+1

**Comment by amakhrov** [comment]
Actually, passing the event into `onChange` wouldn't solve the issue completely. A user can click on the calendar without selecting a date (e.g. navigating between months). And in the scenario above it will as well close the modal.

An alternative suggestion is to introduce a new property: `stopPropagationOnClick: PropTypes.bool`. If this property is `true`, the component will run `e.stopPropagation()` on all mouse clicks inside the calendar.

@martijnrusschen would you consider a PR with the proposed change?

**Comment by tommyalvarez** [comment]
@martijnrusschen In my case i have an date picker input inside a table row **<tr>** and the tr is clickable (it handles the onClick event). So i also need to prevent that clicking the input, bubbles up to the row.

**Comment by krupatel** [comment]
I am facing the similar issue where i have date picker which opens up on a input file type. So it opens the file browser window if we select the date from the area exactly on top of input field.
Any solution to prevent the event propagation ?

**Comment by lukastillmann** [comment]
bump

I am having the same issue. Any solution would be very welcome!

**Comment by ishake** [comment]
I am also having this issue on the time picker portion of this.

**Comment by Kitloo** [comment]
Any solution? @@

**Comment by Muhiq146** [comment]
@tggreene 
Thanks, It worked properly.

The working code :

 ```
<div onClick={(e) => { e.stopPropagation() }}>
            <DatePicker
                {...props}
            />
        </div>
```

If you face any error please share.
