### ISSUE TITLE
Feature request: Maximum date range. 

### ISSUE THREAD

**Issue by jaepage** [Hacker0x01/react-datepicker#494]
It would be nice to have built-in a way to limit the date range that a user can pick to X number of days. Thank you.

**Comment by rafeememon** [comment]
Hey @jaepage, unfortunately I don't think this is something we should support -- the datepicker doesn't do anything special with the `startDate` and `endDate` props other than use them for display.  All date selections propagate directly out via `onChange` to the consumer who can then decide how to set the range props.

I can think of a couple ways to implement what you need:

* If, on selecting the end date, the date from `onChange` is more than x days from the start date, do nothing
* Set `maxDate` to `startDate` + x days so that invalid days are disabled

Let me know if one of those solutions would work for you.

**Comment by jaepage** [comment]
Yes, in the short term, we'll likely do something like your latter suggestion. Just thought I'd mention the feature, however, for your consideration. Thank you.
