### ISSUE TITLE
Custom Input/Multi Date Format

### ISSUE THREAD

**Issue by Haemoglobin** [Hacker0x01/react-datepicker#560]
Hi, 

I'm thinking of using the new custom input functionality (https://github.com/Hacker0x01/react-datepicker/issues/529) in order to support multiple date formats (https://github.com/Hacker0x01/react-datepicker/issues/448). 

I need the ability to enter a variety of things like 1/9/2016 01/09/2016 01092016 01-09-2016 etc. 

First question, is there a reason that moment is set to strict mode parsing at this line https://github.com/Hacker0x01/react-datepicker/blob/v0.25.0/src/date_input.jsx#L56 ? If it was relaxed that might be all I need.   

However, with that in, I'm thinking of parsing/reformatting the date myself in a custom input element and raising onChange using the format that react-datepicker is configured to use? Do you think that will work? 
If so, do you know when the next release will be published that includes custom input? 

Thanks, 
Hamish

**Comment by luggage66** [comment]
You can accept multiple import formats by providing an array to the `dateFormat` property. The first format will be the displayed format.

e.g.

```js
<DatePicker dateFormat={[ 'D/M/YYYY', 'DDMMYYYY', 'DD-MM-YYYY' ]} />
```

Note that as soon as the user types a value that is valid in **any** of those formats, it'll reformat and put the cursor at the end.

**Comment by luggage66** [comment]
Nevermind, I don't thing this is a solution. If you accept for M/D/YY and M/D/YYYY then as soon as you type two digits for a year, it assumes the whole year. If you tried to type "1999" if would assume you meant "2019".

**Comment by Haemoglobin** [comment]
I managed to get it working with the custom input in the end, but it wasn't entirely easy to get working due to various issues, the cursor problem you mentioned for example

**Comment by aij** [comment]
For me, the problem is that as soon as the string is parseable as a date (Eg: 10/10/19) it sends on onChange event, and we feed the resulting moment back into DatePicker via the selected prop. That highlights the date (2019-10-10) in the mini-calendar (which is good), but it also updates the value prop of the input field (which is bad if the user wasn't done typing, as they end up with Eg: 10/10/201999).

**Comment by aij** [comment]
Hmm, I was trying to fix this, but part of the issue is that `DateInput` is used neither as a controlled input nor an uncontrolled input, but something kind of in between. 

I think the cleaner fix would be to make it a stateless, though after that I'm not sure it would really serve a purpose after that... Do we need to keep DateInput around for backwards compatibility? (In case someone might be using it directly?)

**Comment by rakshitmaini** [comment]
> I managed to get it working with the custom input in the end, but it wasn't entirely easy to get working due to various issues, the cursor problem you mentioned for example

Could you please share code for custom input for displaying multiple dates? I am not able to write one yet, will be really helpful.
Thanks

**Comment by Haemoglobin** [comment]
> > I managed to get it working with the custom input in the end, but it wasn't entirely easy to get working due to various issues, the cursor problem you mentioned for example
> 
> Could you please share code for custom input for displaying multiple dates? I am not able to write one yet, will be really helpful.
> Thanks

I'm sorry - this is so long ago now I cannot remember at all what I did... Seems there were some commits related to this issue though so maybe the component supports it better now.
