### ISSUE TITLE
Moment as a peer dependency

### ISSUE THREAD

**Issue by elliotstokes** [Hacker0x01/react-datepicker#579]
Is it possible to release a version of the datepicker with moment as a peer dependency. I noticed that you currently have a branch with something similar on it:

https://github.com/Hacker0x01/react-datepicker/blob/peer-moment/package.json

I'm finding that if the moment versions don't match exactly then I get two versions of moment bundled.

**Comment by rafeememon** [comment]
Unfortunately changing the dependency to peer is a breaking change, so we can't make it until we release v1.0.  The most likely reason for getting multiple moment installations is that dependency ranges don't have a single version that satisfies both, which won't be fixed by changing to a peer dependency here.
