### ISSUE TITLE
Add option to disable keyboard support

### ISSUE THREAD

**Issue by Voxis** [Hacker0x01/react-datepicker#632]
Is it possible to add options to disable keyboard support?
Keyboard support is a great feature, but at times it prevents users from editing the date text input. 

Or maybe someone can point me to a correct direction
Thanks!

**Comment by mgrdevport** [comment]
Resolved by #702 ?

**Comment by rafeememon** [comment]
Yep, thanks!

**Comment by guidupuy** [comment]
Actually... using the tab key still goes to the month arrows, and pressing enter still goes to the previous or next month. Can we make it so that when `disabledKeyboardNavigation` is added, pressing tab moves to the next field on the page instead of going to the datepicker's month arrows? This is breaking a very basic feature here...
