### ISSUE TITLE
I have problems with integration this plugin in my project

### ISSUE THREAD

**Issue by JohnnyHardman** [Hacker0x01/react-datepicker#693]
Hi!
I'm new with react and i have necessity to use this plugin in my project.
but it doesn't work correctly with my code.
![image](https://cloud.githubusercontent.com/assets/9141987/21850981/e8df2dca-d815-11e6-87a7-4fbd6cec21d7.png)

and when i select any date - it doesn't save it to input field.
can anybody help me with this question?

**Comment by alex-shamshurin** [comment]
Because your input is somehow an uncotrolled component, perhaps, or your callback (onChange) does not set's it. In my project there two values 1) `selectedDate` (which is passed to `selected` property and it's a a `moment` object, and 2)`day` is a value which is bound to input field itself. And there is a link between them. Once user selects date via date picker the appropriate value of `date` must be set and vice versa.
