### ISSUE TITLE
Calendar is shown when refocus window

### ISSUE THREAD

**Issue by erikmoren** [Hacker0x01/react-datepicker#709]
Hi,

How to reproduce (works on the demo site aswell):
1. Select a date in the calendar
2. Switch to another window, or another browser tab, and then back again.
3. Now the calendar pops out.

Anyone knows how do disable so that the calendar wont pop out again? 

Thanks

**Comment by mgrdevport** [comment]
The calendar will pop out again, because the input field of the datepicker regains focus (default browser behaviour), which triggers the open state.

**Possible solution:**
Let the calendar only pop out on click of the input element. 
But then the calendar won't pop out on keyboard navigation. This could be solved by changing the default behaviour of e.g. the ArrowDown event (if calendar is not visible pop it out, otherwise add 1 week).

I would submit a PR if it's ok to change the default behaviour.
