### ISSUE TITLE
how to include this date picker component in my existing project ? please help!

### ISSUE THREAD

**Issue by sathyadhari** [Hacker0x01/react-datepicker#774]

**Comment by ibekavac** [comment]
Can u provide more info on your project?
Do you have existing React project setup up?

Do you use npm?

See https://github.com/Hacker0x01/react-datepicker/blob/master/README.md for Installation part

**Comment by sathyadhari** [comment]
I use grails in my project and not npm. Please assist me if you have any idea .

Thanks .

**Comment by ibekavac** [comment]
Sry I do not have experience with Grails. Maybe something here can help you https://objectcomputing.com/resources/publications/sett/june-2016-using-react-with-grails/

See "Setting up our React environment" part

**Comment by alex-shamshurin** [comment]
You can use nodejs for rendering that part which uses react instead of noshorn and fetch this part of HTML into a Grails taglib class from nodejs server (renderToStaticMarkup). Also you can use more native way for Grails - try https://plugins.grails.org/plugin/grails-isomorphic plugin, if it works well with Grails 3.2.* you can include react into taglib. 

Please let me know if you succeeded
