### ISSUE TITLE
Disable only left/right key navigation?

### ISSUE THREAD

**Issue by Noitidart** [Hacker0x01/react-datepicker#789]
Hi there, thanks for maintaining such an awesome component. Is there anyway to disable only the left/right arrow key nav, *but* keep the up/down key nav?

If we disable it, can we map up/down to do next/prev day instead of week?

Because the left/right arrow keys are used by users to adjust cursor position if they want to type a portion or something.

**Comment by benbcai** [comment]
@Noitidart I don't think there is a way currently to disable only the left/right key navigation. If you would like to reserve the left/right arrow keys for moving the cursor position, you could use the disabledKeyboardNavigation prop but this would also disable the up/down key navigation.

If we do make a change to allow disabling only left/right and make up/down to do next/prev day, that seems counterintuitive to me as the up keep should move the day above the day currently in focus instead of moving it to the left.

**Comment by Noitidart** [comment]
Thanks @benbcai for your reply. Makes sense.

I am coming from Kronos datepicker to here, there they had up/down arrow for moving days. So some do expect it to work like this - https://github.com/dubert/react-kronos/ - but I understand, your module your shot. I am appreciative of it!
