### ISSUE TITLE
Latest version of react-onclickoutside breaks date picker

### ISSUE THREAD

**Issue by darcyadams** [Hacker0x01/react-datepicker#812]
Looks like `react-onclickoutside` released over the weekend `5.11.0` and `5.11.1`. After these releases this error occurs in react-datepicker...
```
react-datepicker/~/react-onclickoutside/~/create-react-class/factory.js
Module not found: Error: Cannot resolve module 'object-assign'
```
Not sure if date picker is misusing an internal portion of `react-onclickoutside` or if `react-onclickoutside` has a critical bug or should have revved the major version with this release. But perhaps you should consider reverting to `5.10.0` as a quick fix?

To anyone blocked by this issue, you can workaround it by adding  this to your project's `package.json`:
`"react-onclickoutside": "5.10.0",`

**Comment by rafeememon** [comment]
Can you try doing a fresh `npm install`?  The latest release of `react-onclickoutside` brings in additional transitive dependencies that are probably missing.

**Comment by darcyadams** [comment]
@rafeememon, thanks for the quick reply, but this broke my build, which does a clean `npm install` every time. FYI, I'm using Webpack 1.x and npm 2.x

**Comment by rafeememon** [comment]
Frustratingly, it looks like [`create-react-class`](https://www.npmjs.com/package/create-react-class) has an implicit dependency on `npm >= 3`.  It brings in [`fbjs`](https://www.npmjs.com/package/fbjs) which itself brings in `object-assign`.  This is fine for `npm >= 3` when dependencies were changed to be installed in a flat structure, but will cause issues for older versions.  However, since `npm 2.x` is two major versions old, I highly recommend upgrading =)

cc @Pomax

**Comment by darcyadams** [comment]
thanks again, that info is much appreciated. Upgrading npm is on our to-do list, so I guess it just got a bump up the priority list. This is the first time we have encountered a module that has broken compatibility with npm 2.

**Comment by Pomax** [comment]
commenting due to the cc: npm2 only comes with a version of node that was known to go out of LTS this month for the last 18 months, so if you're still using it, it's *really* time to put "make our code run on the latest LTS" a priority. The current LTS version of Node (6.x), which comes bundled with npm3, and has already been the active LTS for the last six months.
