### ISSUE TITLE
How to retrieve the topmost dom node of datepicker?

### ISSUE THREAD

**Issue by delijah** [Hacker0x01/react-datepicker#823]
I would like to retrieve the topmost dom node of the datepicker. How can i do that?

**Comment by rafeememon** [comment]
You can probably use `ReactDOM.findDOMNode`: https://facebook.github.io/react/docs/react-dom.html#finddomnode

**Comment by delijah** [comment]
Yes, but it is not recommended to use ReactDOM.findDOMNode. I would prefer a more appropriate way of doing this.

**Comment by rafeememon** [comment]
There is no more appropriate solution unfortunately; the "React way" is to not be concerned with DOM nodes at all.

**Comment by delijah** [comment]
Passing up the dom node to the parent component would be the recommended way how i understand this: https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components

**Comment by rafeememon** [comment]
The page also mentions that if the child is a component class, the ref receives the component instance, not the DOM node.  If you need the DOM node of a third-party component I think you're working at the wrong level of abstraction (which is why the approach isn't recommended) but the escape hatch is `findDOMNode`.
