### ISSUE TITLE
regression: on blur date is not formatted

### ISSUE THREAD

**Issue by obartra** [Hacker0x01/react-datepicker#837]
Seems to be a regression from the bug fix to [Avoid reformatting user input as they type](https://github.com/Hacker0x01/react-datepicker/commit/304e408d7940ccb0edaaae5935e0e2417757b03f) from 0.44 to 0.46. On blur, date is no longer formatted.

An easy way to test it is to set the date to `4.23.17` and then press `tab` on the first example.

In version 0.44 the date is formatted correctly (changes to `4/23/17`), in version 0.46 it stays as `4.23.17`.

Behavior is correct with hash [efa7ed](https://github.com/Hacker0x01/react-datepicker/commit/efa7edc043f04db8ed0a29365e0300c797be06e9) but broken at [bae0b5](https://github.com/Hacker0x01/react-datepicker/commit/bae0b570c452f339d003ef744fff09b45a5a39ce).

**Comment by spacebaboon** [comment]
I've also found this. Users are able to enter invalid dates, e.g. typing extra characters the end of a valid date. the invalid date stays in the input field.

reverting to 0.44.0 has fixed it for now. the behaviour in 0.44.0 is to revert to the previous good value if the date is invalid, which is what I'd expect.

**Comment by aij** [comment]
@spacebaboon I had assumed silently discarding user input was a bug rather than behavior anyone would want. (Much less as the default.)

You can still get the old behavior if needed via the `onChangeRaw`, `onBlur`, and `value` props, though I would highly recommend doing *something* to let the user know the date they entered is invalid / being ignored. (Which was not possible in the older version.)

@obarta The previous behavior was to reformat your example as soon as the user hit `7`, before knowing whether it was to be followed by `tab` or `78`. (Which meant that, when combined with silently discarding invalid dates, when a user entered `4.23.1778<tab>`, they would end up with `04/23/2017` instead, and no indication that there was a problem.)

**Comment by obartra** [comment]
Hi @aij, thanks for the reply.

I agree that we don't want to format on the invalid date case. When the date is valid though (as in `moment('4.23.1778', ['MM/DD/YYYY']).isValid() === true`), I think it makes sense to format it to follow the mask defined.

If this is intentional and `4.23.1778` is not valid for `react-datepicker` when the mask is `MM/DD/YYYY`,  it may be worth documenting the differences between what `moment.js` and `react-datepicker` consider valid.

Imo the expected behavior would be to keep them consistent

**Comment by aij** [comment]
@obartra I actually thought about doing that, but `onBlur` didn't seem quite right. Reformatting user input to the preferred format seems like it would be a friendly confirmation, but only when the user is *actually* done entering text.

`onBlur` happens not only when a user hits tab or clicks elsewhere on the page, but also switches tabs/windows and comes back. (such as to check their calendar) That's probably enough of an edge case that it could be ignored though...

**Comment by obartra** [comment]
well, if we leave incomplete/invalid dates untouched that shouldn't be an issue. Is this something you are considering implementing?

**Comment by martijnrusschen** [comment]
This looks like a bug, is this still happening?

**Comment by cadc** [comment]
i fixed this by adding an onBlur event that clears the datepicker inputValue using refs
```
handleBlur() {
    this.datepicker.setState({ inputValue: null });
}
render() {
    return <DatePicker ref={datepicker => {this.datepicker = datepicker}} onBlur={this.handleBlur}/>
}
```
