### ISSUE TITLE
Where is no option to hide year or month from the header.

### ISSUE THREAD

**Issue by unlabeled** [Hacker0x01/react-datepicker#851]
It is possible to have date format like "MM/DD" if you don't need a year, but there is no option to hide a year (or month) from datepicker__header. I guess it needs options to hide either of them or even easier just to have separate classes for month and year. Then it would be possible not only hide them but to have month and year with the different styles as well.

**Comment by rafeememon** [comment]
The date format of the header can be set with [dateFormatCalendar prop](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md#dateformatcalendar).  I don't think it would be wise to build out infrastructure around separating the month and year because it limits the flexibility (whereas moment supports this flexibility OOTB) and it seems like a contrived use case IMO.  Keep in mind that a calendar depends on the month and year to determine its layout; if what you really want is a table of numbers that should be built a la carte =)
