### ISSUE TITLE
triangle position can not customized?

### ISSUE THREAD

**Issue by lukastong** [Hacker0x01/react-datepicker#950]
why can't i change the triangle position, should you expose a prop, to change the triangle position?
 such as float right or like that

**Comment by tohjustin** [comment]
You should be able to change the triangle position easily by overwriting the CSS `margin` attributes defined inside `.react-datepicker-popper` & `.react-datepicker__triangle`. (See https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss)

If you need more help on this, try posting a [jsFiddle](https://jsfiddle.net/) or [codepen](https://codepen.io) example so we can help you out =)

**Comment by blazebarsamian** [comment]
@tohjustin I actually think the triangle position should be in a :before around the input so that the triangle will be displayed relative to the input. Take a look at [airbnb's datepicker](https://github.com/airbnb/react-dates) and how they make the pip so that its not always in the same position. 

For example, this is done with Airbnb's React-dates:
<img width="325" alt="screen shot 2017-07-27 at 10 41 16 am" src="https://user-images.githubusercontent.com/9321193/28679401-abe43d82-72b8-11e7-94a2-ae74d8a3efa1.png"> <img width="325" alt="screen shot 2017-07-27 at 10 41 04 am" src="https://user-images.githubusercontent.com/9321193/28679400-abddb2f0-72b8-11e7-959a-f16005584d47.png">

We needed the functionality to select years so we switched to using this datepicker. The only problem is that the triangle is fixed and doesnt point to the right input. 

Examples using react-datepicker:
<img width="325" alt="screen shot 2017-07-27 at 10 50 15 am" src="https://user-images.githubusercontent.com/9321193/28679749-ce6f35cc-72b9-11e7-992f-3e3f56267bed.png"> <img width="325" alt="screen shot 2017-07-27 at 10 50 30 am" src="https://user-images.githubusercontent.com/9321193/28679750-ce720b08-72b9-11e7-83bf-76539211ed41.png">

**NOTE:** the main source of this issue is because we had to use the popperModifiers to prevent overflow outside of the viewport. Otherwise it looks like this with the calendar running off screen: 
<img width="325" alt="screen shot 2017-07-27 at 10 56 17 am" src="https://user-images.githubusercontent.com/9321193/28679947-620a19fa-72ba-11e7-9057-d46e2b4f2842.png">

**Comment by blazebarsamian** [comment]
This is probably a separate issue: but on mobile the preventOverflow modifier just overlays everything on the screen including the source input.
<img width="191" alt="screen shot 2017-07-27 at 11 19 57 am" src="https://user-images.githubusercontent.com/9321193/28681220-5da85e9a-72be-11e7-97e2-74eb9f0bdbc0.png">

But if you don't use the preventOverflow modifier, the UX on mobile is extremely aggravating.

![jul-27-2017 11-40-40-4](https://user-images.githubusercontent.com/9321193/28681849-8ddf2cc2-72c0-11e7-8625-8654ae011c8c.gif)

**Comment by iamjoshfrank** [comment]
for mobile, would much prefer the preventOverflow option that covers the inputs than have the annoying experience in your animated screen share.

**Comment by blazebarsamian** [comment]
This is probably a separate issue: but on mobile the preventOverflow modifier just overlays everything on the screen including the source input.
<img width="191" alt="screen shot 2017-07-27 at 11 19 57 am" src="https://user-images.githubusercontent.com/9321193/28681220-5da85e9a-72be-11e7-97e2-74eb9f0bdbc0.png">

But if you don't use the preventOverflow modifier, the UX on mobile is extremely aggravating.

![jul-27-2017 11-53-10-5](https://user-images.githubusercontent.com/9321193/28682422-80eeee4c-72c2-11e7-85e5-ae58e9b7dfb7.gif)

**Comment by tohjustin** [comment]
@blazebarsamian Really nice examples you have there! It would definitely be ideal that the triangle position behaves similar to the Airbnb's one.

I'm guessing that you're using this in your project at your workplace, it would be great if you can create a PR for this so that it gets fixed asap for your team 😄 

As for your `preventOverflow` modifier issue, I think it's a better idea to create another issue so that we can discuss & address it separately?
