### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by yamat124** [Hacker0x01/react-datepicker#972]
Datepicker is not working with React 16.0.0 Beta 1. I was getting errors on PropTypes in the react-datepicker.min.js file.

**Comment by martijnrusschen** [comment]
Can you be more specific and post the errors here?

**Comment by yamat124** [comment]
Figure out it was a webpack include issue with an older version.

**Comment by alex-shamshurin** [comment]
We must update proptypes package:

```
import React from 'react'
import PropTypes from 'prop-types'
```

**Comment by rafeememon** [comment]
I think this is going to be trickier than just updating the proptypes package.  React is declared as a peer dependency supporting two different major versions (0.x and 15.x).  Ideally, the package versions of `react` and `prop-types` should match.  I'm not exactly sure if there's some dependency combination that ensures that.  I'm reopening this issue so that we can figure out a solution.

**Comment by aij** [comment]
FWIW, We're currently on React 15.1.0, which doesn't use the `prop-types` package. The only harm in using components that use the `prop-types` package seems to be that we get deprecation warnings about how calling prop types directly is not supported. (They're somewhat misleading in that they blame the render method of a component rather than blaming React itself for the deprecated invocation.)

I do not know how it interacts with 0.14.

Do we actually support 0.14? The README would appear to indicate 15.5 is required for newer versions of `react-datepicker`, though `package.json` still says `^0.14.0 || ^15.0.0`.

**Comment by dimitropoulos** [comment]
for notoriety of the impact of this issue: +1 if this is preventing you from using React 16 (now that it's released)

**Comment by Baldrs** [comment]
Any workaround to make it work with react 16? This is the only incompatible library that I have in my dependencies

**Comment by bjankord** [comment]
There is an open PR to add compatibility with react v16 here: https://github.com/Hacker0x01/react-datepicker/pull/1047 @martijnrusschen @rafeememon would you have some time to take a look?

**Comment by jeffijoe** [comment]
I'm also having issues with React 16:

![image](https://user-images.githubusercontent.com/2505474/31382963-9bc0a404-adb9-11e7-809b-e8c03eb1407f.png)

**Comment by rufman** [comment]
Looks like https://github.com/souporserious/react-popper/pull/59 is merged, so updating to the latest version will resolve the issue.

**Comment by pawarvijay** [comment]
### Still Its giving error with react 16 ,  am i missing anything

```
toms-Macbook:~ tom$ cd fireworks/
toms-Macbook:fireworks tom$ clear
toms-Macbook:fireworks tom$ mkdir myproject
toms-Macbook:fireworks tom$ cd myproject/
toms-Macbook:myproject tom$ npm init -y
toms-Macbook:myproject tom$ npm install react react-dom react-datepicker --save
myproject@1.0.0 /Users/tom/fireworks/myproject
├─┬ react@16.0.0
│ ├─┬ fbjs@0.8.16
│ │ ├── core-js@1.2.7
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.7.3
│ │ │ │ ├─┬ encoding@0.1.12
│ │ │ │ │ └── iconv-lite@0.4.19
│ │ │ │ └── is-stream@1.1.0
│ │ │ └── whatwg-fetch@2.0.3
│ │ ├─┬ promise@7.3.1
│ │ │ └── asap@2.0.6
│ │ ├── setimmediate@1.0.5
│ │ └── ua-parser-js@0.7.17
│ ├─┬ loose-envify@1.3.1
│ │ └── js-tokens@3.0.2
│ ├── object-assign@4.1.1
│ └── prop-types@15.6.0
├─┬ react-datepicker@0.57.0
│ ├── classnames@2.2.5
│ ├── moment@2.19.1
│ ├── *UNMET PEER DEPENDENCY react@^15.5.x
│ ├── UNMET PEER DEPENDENCY react-dom@^15.5.x
│ ├── react-onclickoutside@6.0.0
│ └─┬ react-popper@0.7.4
│   └── popper.js@1.12.6
└── react-dom@16.0.0

npm WARN react-onclickoutside@6.0.0 requires a peer of react@^15.5.x but none was installed.
npm WARN react-onclickoutside@6.0.0 requires a peer of react-dom@^15.5.x but none was installed.
npm WARN myproject@1.0.0 No description
npm WARN myproject@1.0.0 No repository field.
```

**Comment by bjankord** [comment]
@martijnrusschen Can we get a release for this published out to npm?

**Comment by martijnrusschen** [comment]
Done.
