### ISSUE TITLE
Width problem in FireFox

### ISSUE THREAD

**Issue by AnderssonChristian** [Hacker0x01/react-datepicker#994]
I am using react-datepicker v0.53.0 and I'm getting the following results in my application:

Chrome:
![skarmavbild 2017-08-17 kl 09 00 11](https://user-images.githubusercontent.com/12988898/29400331-4bee6030-832d-11e7-9983-39405e0a7270.png)

Firefox:
![skarmavbild 2017-08-17 kl 09 07 20](https://user-images.githubusercontent.com/12988898/29400339-520757ba-832d-11e7-80a6-57f658887549.png)

Also, the language settings seem to have reset from Swedish (as seen in Chrome) to English in Firefox. I'm using FF version 55.0.2 (OS X).

**Comment by tohjustin** [comment]
Hi @AnderssonChristian! I will try to reproduce this behavior on my side and create a PR to fix it.

Also, is it possible to provide the props that you're passing into the `<datepicker />` component? =0

**Comment by tohjustin** [comment]
@AnderssonChristian I wasn't able to reproduce the behavior on Firefox, not sure how different is my setup compared to yours... https://codesandbox.io/embed/7mn4p25rlj

**Comment by AnderssonChristian** [comment]
@tohjustin Sure!

Here's the relative JSX:

```
<div>
   <div>
      <div className="datepicker-wrapper">
         <DatePicker dateFormat="YYYY/MM/DD" showTodayButton={'Idag'} minDate={moment().startOf('day')} locale='sv-se' selected={moment(this.state.start_date)} onChange={this._handleStartDateChange} />
      </div>
   </div>
   <div>
      <div className="datepicker-wrapper">
         <DatePicker dateFormat="YYYY/MM/DD" showTodayButton={'Idag'} minDate={moment().endOf('day').add(1, 'days')} locale='sv-se' selected={moment(this.state.end_date)} onChange={this._handleEndDateChange} />
      </div>
   </div>
</div>
```

Upon further experimentation, I found that going back to v0.48 fixes the problem, but v0.49 and later, breaks it. It must be something with the migration to tether.io; not sure what though.

**Comment by tohjustin** [comment]
Hi @AnderssonChristian, I tried using the snippet + datepicker props above but still couldn't get the layout bug that you have indicated =S 

<img width="366" alt="screenshot ii firefox 55 0 3 - osx" src="https://user-images.githubusercontent.com/8844886/29747274-5e421a82-8aa9-11e7-87dd-37ffff81e197.png">

Here's how could get my project (used for the screenshot above) on your local machine:
```bash
git clone https://github.com/tohjustin/react-datepicker react-datepicker-issue994
cd react-datepicker-issue994/examples/hello-world
git checkout issue-994 # my project branched from v0.53.0 release
yarn && yarn run start # browse http://localhost:3000/
```

Yep, migration to `tether.io` breaks the react-datepicker's API (you mentioned earlier that v0.48 fixes the problem) but currently I'm suspecting that it's a CSS bug on your side otherwise we should have been able to see the examples on the [project's github-page](https://hacker0x01.github.io/react-datepicker/) to be broken on FF.

The best way to confirm the actual cause of it is to provide me a link to your project so that I can clone it & start looking at the issue >_<.

**Comment by AnderssonChristian** [comment]
I'm afraid I cannot provide you with a link to the project, because the project is private.

I did run a new environment, as you suggested, and it worked fine. It's still weird to me though how a previous version works, while the newer doesn't. 

You might indeed be right though. I'll have a closer look and get back, if I find the issue.

Thanks.

**Comment by tohjustin** [comment]
@AnderssonChristian Sounds good, let me if you need any help on this =)

**Comment by Mukhammadali** [comment]
Hi @AnderssonChristian! I also faced with the same issue on chrome as well. but I tracked the datepicker main div container and could fix it by changing display attribute value to block.

**Comment by Vilkku** [comment]
I'm having the same issue. Again, it's unfortunately not a project I can share with you at the moment, but it seems the issue comes from a parent element having a width and a position.

For example, on the demo page (https://hacker0x01.github.io/react-datepicker/), using the inspector give .hero__content width: 100px; and position: relative;.

I am using the datepicker as a part of a form, so the input has a container that is not that wide, just enough to fit a date. I am using Foundation and their CSS grid, so it would be great if there was a solution that didn't involve me modifying the framework's CSS.

**Comment by Mukhammadali** [comment]
@vikku use Chrome dev tools. And identify main parent divs give them display block attribute. Try from top diva to bottom you can fix it with this

**Comment by Vilkku** [comment]
Setting display: block; does not fix it. I did it manually once using DevTools, and then again with jQuery (which is available on the page) $('.react-datepicker').parents().css('display', 'block');, verified that it did indeed set display: block; and all parents, and still the same issue.

I believe that having a parent with a pretty narrow width is part of the issue, maybe that's unique for me?

**Comment by Mukhammadali** [comment]
@vilkku can I see your code? Can you share?

**Comment by Vilkku** [comment]
> can I see your code? Can you share?

Unfortunately, no. But it's really easy to reproduce it on the demo page (https://hacker0x01.github.io/react-datepicker/). Just give give .hero__content width: 100px; and position: relative;, I was unable to get the datepicker to display properly after that even after setting display: block; on all parents.
